import { Point3, Plane, UnitElement, Matrix16 } from '@ts3d-hoops/common';
import { DataKey, InclusionKey, InstanceKey, MasterModelKey, MeshKey, ModelKey } from '@ts3d-hoops/streamcache';
import { AttributeType, PmiSubType, PmiTopoRef, UserDataIndex, GenericId, BodyId } from '../../../types';
import { VersionNumber } from '../../utils';
import { AssemblyData, AssemblyDataHeader, AssemblyDataHeaderVersion } from '../AssemblyData';
import { ProductBits } from '../node/ProductOccurrence';
import { AuthoredNodeId } from '../NodeId';
import { AuthoredLayerId } from '../node-data/types';
import { AttributeParseBits, LayerParseBits, NodeParseBits1, NodeParseBits2, PmiParseBits, RelationshipParseBits, ViewParseBits } from './types';
import { PmiType } from '../node/types';
import { BodyType } from '../node/RepresentationItem';
import { ScKeyRemapper } from './ScKeyRemapper';
import { GenericTypeId, GenericTypeMaps } from '../context/AttachContext';
import { EdgeType, FaceType } from '../../SubentityProperties';
import { PhantomMember } from '../../types';
import { AnyBodyModifierBits } from '../types';
export declare class NodeParseBits {
    hasBits1(bits: NodeParseBits1): boolean;
    hasBits2(bits: NodeParseBits2): boolean;
    parseBits1(parser: AssemblyDataParser): void;
    parseBits2(parser: AssemblyDataParser): void;
    private _bits1;
    private _bits2;
}
export declare class AssemblyVisibility {
    constructor(shown: boolean, removed: boolean);
    readonly shown: boolean;
    readonly removed: boolean;
}
export declare class AssemblyDataParser {
    constructor(assemblyData: AssemblyData);
    hasNext(): boolean;
    parseCount_32(): number;
    parseIndex_32(): number;
    parseAssemblyDataVersion(components: number): VersionNumber;
    parseAssemblyDataHeaderVersion(): AssemblyDataHeaderVersion;
    parseVisibility(): AssemblyVisibility;
    parseProductBits(): ProductBits;
    parseUnits(): UnitElement[];
    parseCString(): string;
    parseUInt32(): number;
    parseInt32(): number;
    parseBytes(count: number): Uint8Array;
    parseNodeId(): AuthoredNodeId;
    parseLayerId(): AuthoredLayerId;
    parseGenericTypes(): GenericTypeMaps;
    parseGenericTypeId(): GenericTypeId;
    parseGenericId(): GenericId;
    parseModifiers(): AnyBodyModifierBits;
    parseBodyRef(): BodyId;
    private _parseScKey;
    parseDataKey(): DataKey;
    parseInstanceKey(): InstanceKey;
    parseMeshKey(): MeshKey;
    parseModelKey(remapper: ScKeyRemapper | null): ModelKey;
    parseInclusionKey(remapper: ScKeyRemapper | null, effectiveModelKey: ModelKey | MasterModelKey): InclusionKey;
    parseMatrix(): Matrix16;
    private _parseInt_8;
    private _parseUint_8;
    private _parseUint_32;
    private _parseInt_32;
    private _parseFloat_32;
    private _parseFloat_64;
    parseFloat_32(): number;
    parseFloat_64(): number;
    parseAttributeType(): AttributeType;
    parseNodeParseBits(): NodeParseBits;
    parseViewParseBits(): ViewParseBits;
    parsePmiParseBits(): PmiParseBits;
    parseLayerParseBits(): LayerParseBits;
    parseAttributeParseBits(): AttributeParseBits;
    parseRelationshipParseBits(): RelationshipParseBits;
    parseBoolean(): boolean;
    parsePoint3_32(): Point3;
    parsePoint3_64(): Point3;
    parsePlane3_32(): Plane;
    parsePmiType(): PmiType;
    parsePmiSubType(): PmiSubType;
    parsePmiTopoRef(): PmiTopoRef;
    parseBodyType(): BodyType;
    parseFaceType(): FaceType;
    parseEdgeType(): EdgeType;
    parseUserDataIndex(): UserDataIndex;
    getHeader(): AssemblyDataHeader | null;
    protected readonly __AssemblyDataParser: PhantomMember;
    private readonly _bytes;
    private readonly _header;
    private readonly _dataView;
    private _currentPos;
}
