import { IRenderOptionsService, PointSizeUnit, RenderOptionsServiceConfiguration, VerticalGradient } from './types';
import { core } from '@ts3d-hoops/web-viewer';
export default class RenderOptionsService extends EventTarget implements IRenderOptionsService {
    readonly serviceName: "RenderOptionsService";
    private _webviewer?;
    private _callbackMap;
    private _webViewerReady;
    private _splatRenderingEnabled;
    private _splatRenderingSize;
    private _splatRenderingPointSizeUnit;
    static readonly DefaultConfig: RenderOptionsServiceConfiguration;
    constructor();
    private bind;
    private unbind;
    get webViewer(): core.IWebViewer | undefined;
    set webViewer(value: core.IWebViewer | undefined);
    private sceneReady;
    getMinimumFramerate(): Promise<number>;
    setMinimumFramerate(value: number): Promise<void>;
    getHiddenLineOpacity(): number;
    setHiddenLineOpacity(opacity: number): void;
    getShowBackfaces(): boolean;
    setShowBackfaces(show: boolean): Promise<void>;
    getAmbientOcclusionEnabled(): boolean;
    setAmbientOcclusionEnabled(enabled: boolean): Promise<void>;
    getAmbientOcclusionRadius(): number;
    setAmbientOcclusionRadius(radius: number): Promise<void>;
    getAntiAliasingEnabled(): boolean;
    setAntiAliasingEnabled(enabled: boolean): Promise<void>;
    getBloomEnabled(): boolean;
    setBloomEnabled(enabled: boolean): void;
    getBloomIntensity(): number;
    setBloomIntensity(intensity: number): void;
    getBloomThreshold(): number;
    setBloomThreshold(threshold: number): void;
    getSilhouetteEnabled(): boolean;
    setSilhouetteEnabled(enabled: boolean): void;
    getReflectionEnabled(): boolean;
    setReflectionEnabled(enabled: boolean): void;
    getShadowEnabled(): boolean;
    setShadowEnabled(enabled: boolean): Promise<void>;
    getShadowInteractive(): boolean;
    setShadowInteractive(interactive: boolean): void;
    getShadowBlurSamples(): number;
    setShadowBlurSamples(samples: number): void;
    getSplatRenderingEnabled(): boolean;
    setSplatRenderingEnabled(enabled: boolean): Promise<void>;
    getSplatRenderingSize(): number;
    setSplatRenderingSize(size: number): Promise<void>;
    getSplatRenderingPointSizeUnit(): PointSizeUnit;
    setSplatRenderingPointSizeUnit(unit: PointSizeUnit): Promise<void>;
    private updateSplatRenderingEnabled;
    getEyeDomeLightingEnabled(): Promise<boolean>;
    setEyeDomeLightingEnabled(enabled: boolean): Promise<void>;
    getBackgroundColor(): VerticalGradient;
    setBackgroundColor(color: VerticalGradient): Promise<void>;
    resetConfiguration(obj?: object): Promise<void>;
}
