import { IResettableConfigurationService, IService } from '../types';
export declare const PointSizeUnitValues: readonly ["Screen Pixels", "CSS Pixels", "World", "Proportion Of Screen Width", "Proportion Of Screen Height", "Proportion Of Bounding Diagonal"];
export type PointSizeUnit = (typeof PointSizeUnitValues)[number];
export declare function isPointSizeUnit(obj: unknown): obj is PointSizeUnit;
export interface VerticalGradient {
    top?: string;
    bottom?: string;
}
export declare function isVerticalGradient(obj: unknown): obj is VerticalGradient;
export type RenderOptionsServiceConfiguration = {
    minimumFramerate: number;
    hiddenLineOpacity: number;
    showBackfaces: boolean;
    ambientOcclusionEnabled: boolean;
    ambientOcclusionRadius: number;
    antiAliasingEnabled: boolean;
    bloomEnabled: boolean;
    bloomIntensity: number;
    bloomThreshold: number;
    silhouetteEnabled: boolean;
    reflectionEnabled: boolean;
    shadowEnabled: boolean;
    shadowInteractive: boolean;
    shadowBlurSamples: number;
    splatRenderingEnabled: boolean;
    splatRenderingSize: number;
    splatRenderingPointSizeUnit: PointSizeUnit;
    eyeDomeLightingEnabled: boolean;
    backgroundColor: VerticalGradient;
};
export declare function isRenderOptionsServiceConfiguration(obj: unknown): obj is RenderOptionsServiceConfiguration;
export interface IRenderOptionsService extends IService, IResettableConfigurationService {
    getMinimumFramerate(): Promise<number>;
    setMinimumFramerate(value: number): Promise<void>;
    getHiddenLineOpacity(): number;
    setHiddenLineOpacity(opacity: number): void;
    getShowBackfaces(): boolean;
    setShowBackfaces(show: boolean): Promise<void>;
    getAmbientOcclusionEnabled(): boolean;
    setAmbientOcclusionEnabled(enabled: boolean): Promise<void>;
    getAmbientOcclusionRadius(): number;
    setAmbientOcclusionRadius(radius: number): Promise<void>;
    getAntiAliasingEnabled(): boolean;
    setAntiAliasingEnabled(enabled: boolean): Promise<void>;
    getBloomEnabled(): boolean;
    setBloomEnabled(enabled: boolean): void;
    getBloomIntensity(): number;
    setBloomIntensity(intensity: number): void;
    getBloomThreshold(): number;
    setBloomThreshold(threshold: number): void;
    getSilhouetteEnabled(): boolean;
    setSilhouetteEnabled(enabled: boolean): void;
    getReflectionEnabled(): boolean;
    setReflectionEnabled(enabled: boolean): void;
    getShadowEnabled(): boolean;
    setShadowEnabled(enabled: boolean): void;
    getShadowInteractive(): boolean;
    setShadowInteractive(interactive: boolean): void;
    getShadowBlurSamples(): number;
    setShadowBlurSamples(samples: number): void;
    getSplatRenderingEnabled(): boolean;
    setSplatRenderingEnabled(enabled: boolean): Promise<void>;
    getSplatRenderingSize(): number;
    setSplatRenderingSize(size: number): Promise<void>;
    getSplatRenderingPointSizeUnit(): PointSizeUnit;
    setSplatRenderingPointSizeUnit(unit: PointSizeUnit): Promise<void>;
    getEyeDomeLightingEnabled(): Promise<boolean>;
    setEyeDomeLightingEnabled(enabled: boolean): Promise<void>;
    getBackgroundColor(): VerticalGradient;
    setBackgroundColor(color: VerticalGradient): Promise<void>;
    resetConfiguration(obj?: object): Promise<void>;
}
