import { Box, Color, Point2, Point3, Matrix, Plane, Ray, Vector3, Vector4, Matrix16, Matrix12 } from '@ts3d-hoops/common';
import { Camera } from '../../Camera';
import { Light, PointLight } from '../../Light';
import { SetShaderOptions, UniformDescription, MeshId, DrawStrategy, TransparencyMode, CullingVectorSpace, LinePatternLengthUnit, LightKey, SimpleReflectionAttenuationUnit, SessionType, AttachScope, InclusionKey, ModelKey, DataKey, InstanceIncs, InstanceInc, SetVisibility, InstanceKey, MeshKey, MeshIds, BimType, DrawMode as ScDrawMode, TextureMipMapping, TextureInterpolation, TextureModifier, MatrixInc, DataIds, ImageId, ImageIds, StateFailure, ViewKey } from '@ts3d-hoops/streamcache';
import { MeshData, MeshInstanceData } from '../../MeshData';
import { MeshDataCopy } from '../../MeshDataCopy';
import { IncrementalPickConfig, PickConfig } from '../../PickConfig';
import { SvgConfig } from '../../SvgConfig';
import { CompositeSelectionItem, IncrementalSelectionId, NodeEntitySelectionItem, SelectionItem } from '../../selection';
import { HiddenLineSettings } from '../../settings/HiddenLineSettings';
import { AntiAliasingMode, Projection, ScModelName, RendererType, BlurIntervalUnit, WebViewerConfig, PointSizeUnit, PointShape, ScsUri, ScsBuffer, OverlayAnchor, FaceFaceDistanceItem, InstanceModifier, MetallicRoughnessValue, XRayTransparencyMode, CullingVector, LinePattern, BloomLayerInfo, ComparisonConfig, OverlayUnit, XRayGroup, ElementType, ImageOptions, TextureOptions, Milliseconds, OverlayIndex, IMaterial, MaterialParam } from '../../types';
import { StatisticMap } from '../Statistics';
import { RequestBatchType, CuttingSectionLimits, KeyInfoBy, KeyInfoReturn } from '../types';
import { InitOptions } from './types';
import { IScEngine } from '../../core/IScEngine';
import { ICallbackManager } from '../../core/ICallbackManager';
import { ICuttingSection } from '../../core';
export declare class ScEngine implements IScEngine {
    private readonly _callbackManager;
    private _sc;
    private _sessionType;
    private _matrixCache;
    private _scSelectionManager;
    private _initOptions;
    private _canvasContainers;
    private _canvases;
    private _viewIndices;
    private _canvas2dContexts;
    private _windowSizes;
    private readonly _engineReadyPromise;
    private readonly _sessionStartedPromise;
    private _connectionlessEmpty;
    private _uri;
    private _model?;
    private _sessionToken?;
    private _buffer?;
    private _streamingMode;
    private _rendererType;
    private _meshLevel;
    private _memoryLimit;
    private _boundingPreviewMode;
    private _streamCutoffScale;
    private _loadFinished;
    private _statistics;
    private _cachedTriangleCount;
    private _cachedElementCount;
    private readonly _cuttingSectionToKeyMap;
    private readonly _cappingQuantizationGranularity;
    private _cappingFaceColor;
    private _cappingLineColor;
    private _cappingGeometryVisibility;
    private _cappingNeedsUpdate;
    private _cappingDelayTimeoutId;
    private _cappingDelay;
    private _requestBatchCountByType;
    private _pendingRequestsByType;
    constructor(callbackManager: ICallbackManager, options: WebViewerConfig);
    addView(canvasContainer: HTMLDivElement): Promise<ViewKey>;
    removeView(index: ViewKey): void;
    getViews(): number[];
    getNetworkModelName(): ScModelName;
    logMessage(message: string): void;
    setTimeout(handler: () => void, timeout: number): ReturnType<typeof setTimeout>;
    sleep(duration: Milliseconds): Promise<void>;
    getScsInfo(): ScsUri | ScsBuffer | null;
    private _applyOptions;
    start(canvasContainer: HTMLDivElement, options: InitOptions): boolean;
    setPickTolerance(tolerance: number): void;
    getPickTolerance(): number;
    private _onEngineReady;
    loadFinished(): boolean;
    resetCachedStatistics(): void;
    setAmbientOcclusionEnabled(view_key: ViewKey, enabled: boolean): void;
    setAmbientOcclusionRadius(view_key: ViewKey, radius: number): void;
    setLightingEnabled(view_key: ViewKey, enabled: boolean): void;
    private _fillStatTotalCounts;
    private _updateCachedStats;
    private _toVector3;
    startExplode(incs: InstanceIncs, vector: Point3): void;
    setExplodeMagnitude(magnitude: number): void;
    stopExplode(): void;
    getStatistics(forceUpdate?: boolean): Promise<StatisticMap>;
    setStreamIdleMarker(): Promise<void>;
    hasDepthRange(incs: InstanceIncs): Promise<boolean[]>;
    setDepthRange(incs: InstanceIncs, min: number, max: number): void;
    unsetDepthRange(incs: InstanceIncs): void;
    setDefaultDepthRange(view_key: ViewKey, min: number, max: number): void;
    _getScPlaneArray(cuttingSection: ICuttingSection): Vector4[];
    getCuttingSectionLimits(): CuttingSectionLimits;
    private _addCuttingSection;
    addCuttingSection(cuttingSection: ICuttingSection): Promise<void>;
    removeCuttingSection(cuttingSection: ICuttingSection): Promise<void>;
    removeAllCuttingSections(): void;
    updateCuttingSection(cuttingSection: ICuttingSection): Promise<void>;
    setCappingDelay(delayInMilliseconds: number): void;
    enableCappingIdleCallback(enable: boolean): Promise<boolean>;
    getCappedInstances(): Promise<InstanceIncs>;
    delayCapping(): void;
    setCappingGeometryVisibility(view_key: ViewKey, cappingGeometryVisibility: boolean): void;
    private _regenerateCapping;
    getCappingGeometryVisibility(): boolean;
    private _toRgb;
    private _toRgba;
    setCappingFaceColor(color: Color | null): void;
    setCappingLineColor(color: Color | null): void;
    private _onSessionStarted;
    isInit(): boolean;
    setRemoteEndpoint(uri: string, modelName: ScModelName): void;
    getSessionType(): SessionType;
    private _awaitEmptyLoad;
    loadEmpty(): Promise<void>;
    private _loadEmpty;
    private _loadEmptyScs;
    private _loadEmptyNetwork;
    setProjection(viewKey: ViewKey, projection: Projection): void;
    getViewMatrix(camera: Camera): Matrix;
    getProjectionMatrix(camera: Camera, viewKey: ViewKey): Matrix;
    getFullCameraMatrix(camera: Camera, viewKey: ViewKey): Matrix;
    getPrimaryModelKey(): Promise<ModelKey>;
    getPartsBounding(incs: InstanceIncs, ignoreInvisible: boolean, tightBounding: boolean): Promise<Box>;
    getDrawnPartsBounding(incs: InstanceIncs, viewKey: ViewKey): Promise<Box>;
    getBounding(incs: InstanceIncs, ignoreInvisible: boolean, includeExcluded: boolean, tightBounding: boolean): Promise<Box>;
    getLooseBounding(): Promise<Box>;
    getClientDimensions(viewKey: ViewKey): [number, number];
    getModelBounding(ignoreInvisible: boolean, includeExcluded: boolean, tightBounding: boolean): Promise<Box>;
    pickFromScreen(viewKey: ViewKey, point: Point2, config: PickConfig, isDrawing: boolean): Promise<NodeEntitySelectionItem | null>;
    pickAllFromScreen(viewKey: ViewKey, point: Point2, config: PickConfig, isDrawing: boolean): Promise<NodeEntitySelectionItem[]>;
    compositePickFromScreen(viewKey: ViewKey, point: Point2, config: PickConfig, isDrawing: boolean): Promise<CompositeSelectionItem>;
    beginScreenAreaSelection(viewKey: ViewKey, areaCssMin: Point2, areaCssMax: Point2, config: IncrementalPickConfig): Promise<IncrementalSelectionId>;
    beginRayDrillSelection(viewKey: ViewKey, rayCssOrigin: Point2, rayCssBoxRadius: number, config: IncrementalPickConfig): Promise<IncrementalSelectionId>;
    beginConvexPolyhedronSelection(volumePlanes: Plane[], heuristicOrigin: Point3, config: IncrementalPickConfig): Promise<IncrementalSelectionId>;
    beginSphereSelection(sphereCenter: Vector3, sphereRadius: number, config: IncrementalPickConfig): Promise<IncrementalSelectionId>;
    endIncrementalSelection(handle: IncrementalSelectionId): void;
    advanceIncrementalSelection(handle: IncrementalSelectionId): Promise<SelectionItem[] | null>;
    flushMetaDataCache(): void;
    safeGetMetaDatas(modelKey: ModelKey, dataKey: [DataKey]): Promise<[Uint8Array] | null>;
    safeGetMetaDatas(modelKey: ModelKey, dataKeys: DataKey[]): Promise<Uint8Array[] | null>;
    safeGetMetaData(modelKey: ModelKey, dataKey: DataKey): Promise<Uint8Array | null>;
    safeLoadMetaDatas(ids: DataIds): Promise<void>;
    getDataFromIds(ids: DataIds): Promise<Uint8Array[]>;
    private _getDataFromIds;
    pickFromRay(ray: Ray, config: PickConfig): Promise<NodeEntitySelectionItem | null>;
    pickAllFromRay(ray: Ray, config: PickConfig): Promise<NodeEntitySelectionItem[]>;
    updateCamera(viewKey: ViewKey, camera: Camera): Camera;
    private _toProjection;
    private _toCamera;
    setCamera(viewKey: ViewKey, camera: Camera): void;
    private _setCamera;
    markCameraAsEmpty(viewKey: ViewKey): void;
    setInstancesMatrix(incs: InstanceIncs, matrix: Matrix): void;
    setMatrices(incs: InstanceIncs, matrices: Matrix[]): void;
    highlightParts(incs: InstanceIncs, highlighted: boolean): void;
    highlightElements(incs: InstanceIncs, elementType: ElementType, elementIndex: number, elementCount: number, value: boolean): void;
    getPartHighlighted(incs: InstanceIncs): Promise<boolean[]>;
    getElementHighlighted(incs: InstanceIncs, elementType: ElementType, elementIndex: number): Promise<boolean[]>;
    /**
     * Returns an array of visibility values for the specified element.
     * @param incs The instance that contains the element.
     * @param elementType The type of the element (points, lines, faces).
     * @param elementIndex The index of the element to query the visibility for.
     * @returns A promise that resolves to an array of boolean values indicating the visibility of the specified element.
     * @internal
     */
    getElementVisibility(incs: InstanceIncs, elementType: ElementType, elementIndex: number): Promise<boolean[]>;
    setNodeHighlightColor(viewKey: ViewKey, fillColor: Color | null, outlineColor: Color | null): void;
    setElementHighlightColor(viewKey: ViewKey, fillColor: Color | null, outlineColor: Color | null): void;
    setHighlightColorizeCompression(viewKey: ViewKey, compressionLevel: number): void;
    computeMinimumBodyBodyDistance(inc1: InstanceInc, inc2: InstanceInc): Promise<FaceFaceDistanceItem>;
    computeMininimumFaceFaceDistance(inc1: InstanceInc, face1: number, inc2: InstanceInc, face2: number): Promise<FaceFaceDistanceItem>;
    computeMinimumFaceRayDistance(inc: InstanceInc, faceId: number, ray: Ray): Promise<FaceFaceDistanceItem>;
    computeMinimumFaceLineDistance(inc: InstanceInc, faceId: number, ray: Ray): Promise<FaceFaceDistanceItem>;
    pauseRendering(viewKey: ViewKey, callback?: () => void): void;
    pauseAllRendering(callback?: () => void): void;
    resumeRendering(viewKey: ViewKey): void;
    resumeAllRendering(): void;
    beginRequestBatch(type: RequestBatchType): void;
    endRequestBatch(type: RequestBatchType): void;
    private _flushBatchedRequests;
    private _flushBatchedMetaDataRequests;
    clearHighlight(): void;
    resetColors(): void;
    resetOpacity(): void;
    setPartOpacity(incs: InstanceIncs, opacity: number): void;
    unsetPartOpacity(incs: InstanceIncs): void;
    getPartOpacity(incs: InstanceIncs): (number | null)[];
    getEffectivePartOpacity(incs: InstanceIncs, elementType: ElementType): Promise<number[]>;
    getPartHasTransparency(incs: InstanceIncs): Promise<boolean[]>;
    private _materialDescriptorToMaterial;
    private _toMaterialDescriptor;
    setPartMaterial(incs: InstanceIncs, material: IMaterial): void;
    resetPartMaterial(nodeIds: InstanceIncs, params?: MaterialParam[]): void;
    getPartMaterial(incs: InstanceIncs): Promise<IMaterial[]>;
    setPartColor(incs: InstanceIncs, elementType: ElementType, color: Color): void;
    unsetPartColor(incs: InstanceIncs, elementType: ElementType): void;
    getPartColor(incs: InstanceIncs, elementType: ElementType): Promise<(Color | null)[]>;
    getEffectivePartColor(incs: InstanceIncs, elementType: ElementType): Promise<Color[]>;
    setPartAmbientColor(incs: InstanceIncs, elementType: ElementType, color: Color): void;
    unsetPartAmbientColor(incs: InstanceIncs, elementType: ElementType): void;
    getPartAmbientColor(incs: InstanceIncs, elementType: ElementType): Promise<(Color | null)[]>;
    getPartEffectiveAmbientColor(incs: InstanceIncs, elementType: ElementType): Promise<Color[]>;
    setPartAmbientMix(incs: InstanceIncs, elementType: ElementType, value: number): void;
    setPartEmissiveColor(incs: InstanceIncs, elementType: ElementType, color: Color): void;
    getPartEmissiveColor(incs: InstanceIncs, elementType: ElementType): Promise<(Color | null)[]>;
    getPartEffectiveEmissiveColor(incs: InstanceIncs, elementType: ElementType): Promise<Color[]>;
    unsetPartEmissiveColor(incs: InstanceIncs, elementType: ElementType): void;
    setPartShader(incs: InstanceIncs, vertexSource: string, fragmentSource: string, options?: SetShaderOptions): Promise<void>;
    setPartShaderUniforms(incs: InstanceIncs, uniforms: Record<string, UniformDescription>): void;
    setPartSpecularColor(incs: InstanceIncs, elementType: ElementType, color: Color): void;
    getPartSpecularColor(incs: InstanceIncs, elementType: ElementType): Promise<(Color | null)[]>;
    getPartEffectiveSpecularColor(incs: InstanceIncs, elementType: ElementType): Promise<Color[]>;
    unsetPartSpecularColor(incs: InstanceIncs, elementType: ElementType): void;
    setPartSpecularIntensity(incs: InstanceIncs, elementType: ElementType, value: number): void;
    unsetPartSpecularIntensity(incs: InstanceIncs, elementType: ElementType): void;
    setElementColor(incs: InstanceIncs, elementType: ElementType, elementOffset: number, elementCount: number, color: Color): void;
    unsetElementColor(incs: InstanceIncs, elementType: ElementType, elementOffset: number, elementCount: number): void;
    getElementColor(inc: InstanceInc, elementType: ElementType, elementOffset: number): Promise<[Color | null]>;
    getElementColor(incs: InstanceIncs, elementType: ElementType, elementOffset: number): Promise<(Color | null)[]>;
    getEffectiveElementColor(incs: InstanceIncs, elementType: ElementType, elementOffset: number, viewKey: ViewKey): Promise<Color[]>;
    synchronizeVisibilities(incs: InstanceIncs, visible: boolean): void;
    setPartVisibility(incs: InstanceIncs, visible: boolean, onlyDemanded: boolean): void;
    setElementVisibility(incs: InstanceIncs, elementType: ElementType, elementOffset: number, elementCount: number, visible: boolean): void;
    clearElementVisibility(incs: InstanceIncs, elementType: ElementType): void;
    setVisibilityByAttachment(attachScope: AttachScope, setVisibility: SetVisibility): void;
    requestMeshInstances(incs: InstanceIncs): void;
    getRendererType(): RendererType;
    private _toMeshDataBuilder;
    createMesh(meshData: MeshData): Promise<MeshId>;
    replaceMesh(id: MeshId, data: MeshData): Promise<void>;
    destroyMeshes(meshIds: MeshIds): Promise<void>;
    private _toImageFormat;
    private _validateImage;
    private _pngImageHasAlpha;
    createImage(primaryImage: ImageOptions, thumbnailImage?: ImageOptions): Promise<ImageId>;
    destroyImages(imageIds: ImageIds): Promise<void>;
    _toTextureInterpolation(value: boolean | undefined): TextureInterpolation;
    _toTextureMipMapping(value: boolean | undefined): TextureMipMapping;
    _toTextureModifier(value: number | undefined): TextureModifier;
    setTexture(instanceIncs: InstanceIncs, options: TextureOptions): Promise<void>;
    unsetTexture(incs: InstanceIncs): void;
    createMatrix(elements: Matrix16): Promise<MatrixInc>;
    createIdentityMatrix(): Promise<MatrixInc>;
    createMeshInstance(meshInstanceData: MeshInstanceData): Promise<InstanceInc>;
    destroyLocalInstances(instanceIncs: InstanceIncs): Promise<void>;
    private _fromScCamera;
    getCameraPromise(viewKey: ViewKey): Promise<Camera>;
    getCamera(viewKey: ViewKey): Camera;
    resize(viewKey?: ViewKey): void;
    private _resizeRenderCanvas;
    setFaceVisibility(view_key: ViewKey, faceVisibility: boolean): void;
    setLineVisibility(view_key: ViewKey, lineVisibility: boolean): void;
    getCanvasSize(viewKey: ViewKey): Point2;
    setBackgroundGradient(view_key: ViewKey, top: Color | null, bottom: Color | null): void;
    setBoundingPreviewUnderDrawColor(color: Color, viewKey: ViewKey): void;
    setBoundingPreviewTestedColor(color: Color, viewKey: ViewKey): void;
    setBoundingPreviewEjectedColor(color: Color, viewKey: ViewKey): void;
    setBoundingPreviewUnderDraw(boxes: Box[], viewKey: ViewKey): void;
    setBoundingDebugLevel(level: number, viewKey: ViewKey): void;
    setBoundingPreviewTested(boxes: Box[], viewKey: ViewKey): void;
    setBoundingPreviewEjected(boxes: Box[], viewKey: ViewKey): void;
    setServerRenderQuality(jpegQualityLow: number, jpegQualityHigh: number, scaleLow: number, scaleHigh: number): void;
    setMinimumFramerate(viewKey: ViewKey, value: number): void;
    getMinimumFramerate(viewKey: ViewKey): Promise<number>;
    setBackFacesVisible(view_key: ViewKey, visible: boolean): void;
    setDrawMode(view_key: ViewKey, value: ScDrawMode): void;
    enableHiddenLineRendering(view_key: ViewKey, settings: HiddenLineSettings): void;
    setAntiAliasingMode(view_key: ViewKey, antiAliasingMode: AntiAliasingMode): void;
    setInstanceModifier(instanceModifier: InstanceModifier, incs: InstanceIncs, modifierValue: boolean): void;
    attachModel(attachScope: AttachScope, modelName: ScModelName, inclusionMatrix: Matrix12, attachMeasurementUnit: number, attachInvisibly: boolean): Promise<void>;
    attachScsModelByKey(attachScope: AttachScope, modelKey: ModelKey, inclusionMatrix: Matrix12, attachMeasurementUnit: number, attachInvisibly: boolean): InclusionKey;
    private _attachModels;
    attachScsBuffer(attachScope: AttachScope, buffer: ScsBuffer, inclusionMatrix: Matrix12, attachMeasurementUnit: number, attachInvisibly: boolean, resolveOnFullyLoaded: boolean, cancelUnitMatrix: boolean, autoUnitScale: boolean): Promise<void>;
    feedScsBuffer(attachScope: AttachScope, buffer: ScsBuffer | null): void;
    private _parseKeyInfo;
    instanceKeyInfo(modelKey: ModelKey, by: KeyInfoBy.Model, ret: KeyInfoReturn.AllKeys): Promise<InstanceKey[]>;
    instanceKeyInfo(attachScope: AttachScope, by: KeyInfoBy.Attachment, ret: KeyInfoReturn.AllKeys): Promise<Map<ModelKey, InstanceKey[]>>;
    instanceKeyInfo(modelKey: ModelKey, by: KeyInfoBy.Model, ret: KeyInfoReturn.KeyCountOnly): Promise<[number]>;
    instanceKeyInfo(attachScope: AttachScope, by: KeyInfoBy.Attachment, ret: KeyInfoReturn.KeyCountOnly): Promise<[number]>;
    metaDataKeyInfo(modelKey: ModelKey, byModel: true, keyCountOnly: false): Promise<DataKey[]>;
    metaDataKeyInfo(attachScope: AttachScope, byModel: false, keyCountOnly: false): Promise<Map<ModelKey, DataKey[]>>;
    metaDataKeyInfo(modelKey: ModelKey, byModel: true, keyCountOnly: true): Promise<[number]>;
    metaDataKeyInfo(attachScope: AttachScope, byModel: false, keyCountOnly: true): Promise<[number]>;
    modelKeysFromInclusionKeys(inclusionKeys: InclusionKey[]): Promise<ModelKey[]>;
    detachInclusions(inclusionKeys: InclusionKey[]): Promise<void>;
    resetToEmpty(whitelistInstances: InstanceKey[], whitelistMeshes: MeshKey[]): Promise<void>;
    setDrawStrategy(viewKey: ViewKey, strategy: DrawStrategy): void;
    redraw(viewKey: ViewKey): void;
    disconnectNetwork(): void;
    shutdown(): void;
    getVersionString(): string;
    setAllowHighDpi(allow: boolean): void;
    getAllowHighDpi(): boolean;
    setMeshLevel(incs: InstanceIncs, meshLevel: number): void;
    setMetallicRoughness(incs: InstanceIncs, metallicFactor: number, roughnessFactor: number): void;
    setMetallicRoughnessMaterialOverride(defaultMetallicFactor: number, defaultRoughnessFactor: number): void;
    getMetallicRoughness(incs: InstanceIncs): Promise<(MetallicRoughnessValue | null)[]>;
    unsetMetallicRoughness(incs: InstanceIncs): void;
    setOverlayVisibility(index: OverlayIndex, visibility: boolean, viewKey: ViewKey): void;
    setOverlayCamera(index: OverlayIndex, camera: Camera, viewKey: ViewKey): void;
    destroyOverlay(index: OverlayIndex, viewKey: ViewKey): void;
    private _overlayUnit;
    getMaxOverlayIndex(): OverlayIndex;
    private _overlayAnchor;
    setOverlayViewport(index: OverlayIndex, anchor: OverlayAnchor, x: number, xUnit: OverlayUnit, y: number, yUnit: OverlayUnit, width: number, widthUnit: OverlayUnit, height: number, heightUnit: OverlayUnit, viewKey: ViewKey): void;
    addNodesToOverlay(incs: InstanceIncs, viewKey: ViewKey, index: OverlayIndex): void;
    getInstancesMeshData(inc: InstanceInc): Promise<MeshId>;
    getInstancesMeshData(incs: InstanceIncs): Promise<MeshIds>;
    getInstancesCappingMeshData(inc: InstanceInc): Promise<MeshId>;
    getInstancesCappingMeshData(incs: InstanceIncs): Promise<MeshIds>;
    getMeshData(id: MeshId): Promise<MeshDataCopy>;
    private _toElementType;
    private _toXRayGroup;
    setXRayColor(view_key: ViewKey, group: XRayGroup, element: ElementType, color: Color): void;
    unsetXRayColor(view_key: ViewKey, group: XRayGroup, element: ElementType): Promise<void>;
    setXRayOpacity(view_key: ViewKey, value: number, element?: ElementType): void;
    setXRayTransparencyMode(view_key: ViewKey, value: XRayTransparencyMode): void;
    setGoochBlue(view_key: ViewKey, value: number): void;
    setGoochBaseColorProminence(view_key: ViewKey, value: number): void;
    setGoochYellow(view_key: ViewKey, value: number): void;
    setGoochLuminanceShiftStrength(view_key: ViewKey, value: number): void;
    setToonShadingBandCount(view_key: ViewKey, bandCount: number): void;
    setToonShadingSpecularFactor(view_key: ViewKey, specularFactor: number): void;
    setTransparencyMode(view_key: ViewKey, value: TransparencyMode): void;
    setPointSize(view_key: ViewKey, size: number, unit: PointSizeUnit): void;
    getPointSize(view_key: ViewKey): Promise<[number, PointSizeUnit]>;
    setPointShape(view_key: ViewKey, shape: PointShape): void;
    getPointShape(view_key: ViewKey): Promise<PointShape>;
    setEyeDomeLightingEnabled(view_key: ViewKey, enabled: boolean): void;
    getEyeDomeLightingEnabled(view_key: ViewKey): Promise<boolean>;
    setEyeDomeLightingBlurSamples(view_key: ViewKey, value: number): void;
    getEyeDomeLightingBlurSamples(view_key: ViewKey): Promise<number>;
    setEyeDomeLightingBlurInterval(view_key: ViewKey, value: number): void;
    getEyeDomeLightingBlurInterval(view_key: ViewKey): Promise<number>;
    setEyeDomeLightingBlurEdgeDistance(view_key: ViewKey, value: number): void;
    getEyeDomeLightingBlurEdgeDistance(view_key: ViewKey): Promise<number>;
    setEyeDomeLightingShadingEdgeDistance(view_key: ViewKey, value: number): void;
    getEyeDomeLightingShadingEdgeDistance(view_key: ViewKey): Promise<number>;
    setEyeDomeLightingOpacity(view_key: ViewKey, value: number): void;
    getEyeDomeLightingOpacity(view_key: ViewKey): Promise<number>;
    setDisplayIncompleteFrames(value: boolean, viewKey: ViewKey): void;
    setInteractiveDrawDelay(value: number, viewKey: ViewKey): void;
    setInteractiveDrawLimitIncreaseEnabled(enable: boolean, viewKey: ViewKey): void;
    getInteractiveDrawLimitIncreaseEnabled(viewKey: ViewKey): Promise<boolean>;
    setCullingVector(incs: InstanceIncs, space: CullingVectorSpace, vector: Point3, toleranceDegrees: number): void;
    unsetCullingVector(incs: InstanceIncs): void;
    getCullingVector(incs: InstanceIncs): Promise<(CullingVector | null)[]>;
    private _setStreamCutoffScale;
    setStreamCutoffScale(value: number): void;
    getStreamCutoffScale(): number;
    loseWebGlContext(): boolean;
    triangulatePolygon(polygonPoints: Float32Array | number[], normal: Vector3): Float32Array;
    debug_log(message: string): Promise<void>;
    debug_stateFailure(value: StateFailure): Promise<void>;
    debug_sync(): Promise<void>;
    setLinePattern(incs: InstanceIncs, pattern: LinePattern, patternLength: number, patternLengthUnit: LinePatternLengthUnit): void;
    unsetLinePattern(incs: InstanceIncs): void;
    createFloorplanMesh(incs: InstanceIncs): Promise<InstanceIncs>;
    exportToSvg(config: SvgConfig): Promise<string>;
    beginExportToSvg(config: SvgConfig): Promise<void>;
    advanceExportToSvg(): Promise<string | undefined>;
    waitForImageDecoding(): Promise<void>;
    registerBimInstances(incs: InstanceIncs, bimType: BimType): void;
    setAmbientLightColor(view_key: ViewKey, value: Color): void;
    getLightKeys(view_key: ViewKey): Promise<LightKey[]>;
    getLight(view_key: ViewKey, key: LightKey): Promise<Light | undefined>;
    clearLights(view_key: ViewKey): void;
    addLight(view_key: ViewKey, light: Light): Promise<LightKey>;
    addPointLight(view_key: ViewKey, light: PointLight): Promise<LightKey>;
    removeLight(view_key: ViewKey, key: LightKey): void;
    updateLight(view_key: ViewKey, key: LightKey, light: Light): void;
    setBloomEnabled(view_key: ViewKey, value: boolean): void;
    setBloomThreshold(view_key: ViewKey, value: number): void;
    setBloomThresholdRampWidth(view_key: ViewKey, value: number): void;
    setBloomIntensityScale(view_key: ViewKey, value: number): void;
    private _toBlurIntervalUnit;
    setBloomLayers(view_key: ViewKey, layers: BloomLayerInfo[]): void;
    startComparison(view_key: ViewKey, instanceSet1: InstanceIncs, instanceSet2: InstanceIncs, config?: ComparisonConfig): void;
    endComparison(view_key: ViewKey): void;
    setSimpleShadowColor(view_key: ViewKey, value: Color): void;
    setSimpleShadowEnabled(view_key: ViewKey, value: boolean): void;
    setSimpleShadowOpacity(view_key: ViewKey, value: number): void;
    setGroundPlane(view_key: ViewKey, normal: Point3, position?: Point3): void;
    setSimpleShadowResolution(view_key: ViewKey, pixels: number): void;
    setSimpleShadowBlurSamples(view_key: ViewKey, value: number): void;
    setSimpleShadowBlurInterval(view_key: ViewKey, value: number): void;
    setSimpleShadowInteractiveUpdateEnabled(view_key: ViewKey, value?: boolean): void;
    setSilhouetteColor(view_key: ViewKey, value: Color): void;
    setSilhouetteEnabled(view_key: ViewKey, value?: boolean): void;
    setSilhouetteOpacity(view_key: ViewKey, value: number): void;
    setSilhouetteThreshold(view_key: ViewKey, value: number): void;
    setSilhouetteThresholdRampWidth(view_key: ViewKey, value: number): void;
    setHardEdgeColor(view_key: ViewKey, value: Color): void;
    setHardEdgesEnabled(view_key: ViewKey, value?: boolean): void;
    setHardEdgeOpacity(view_key: ViewKey, value: number): void;
    setHardEdgeThreshold(view_key: ViewKey, value: number): void;
    setHardEdgeThresholdRampWidth(view_key: ViewKey, value: number): void;
    setSimpleReflectionEnabled(view_key: ViewKey, value?: boolean): void;
    setSimpleReflectionBlurInterval(view_key: ViewKey, value: number, unit: BlurIntervalUnit): void;
    setSimpleReflectionBlurSamples(view_key: ViewKey, value: number): void;
    setSimpleReflectionFadeAngle(view_key: ViewKey, degrees: number): void;
    setSimpleReflectionOpacity(view_key: ViewKey, value: number): void;
    setSimpleReflectionAttenuation(view_key: ViewKey, nearDistance: number, farDistance: number, unit?: SimpleReflectionAttenuationUnit): void;
    throttleLoad(newPauseInterval: Milliseconds, throttleDuration: Milliseconds): void;
    private _toVector3Array;
    testPointVisibility(view_key: ViewKey, points: Point3[]): Promise<number[]>;
    setPointVisibilityTest(view_key: ViewKey, points: Point3[]): void;
    setImageBasedLightingEnabled(view_key: ViewKey, value: boolean): void;
    setImageBasedLightingIntensity(view_key: ViewKey, value: number): void;
    private _toMatrix9;
    setImageBasedLightingMatrix(view_key: ViewKey, value: Matrix): void;
    setImageBasedLightingEnvironment(view_key: ViewKey, data: Uint8Array): void;
    setImageBasedLightingEnvironmentToDefault(view_key: ViewKey): void;
    setLineJitterEnabled(view_key: ViewKey, value: boolean): void;
    setLineJitterInstanceCount(view_key: ViewKey, value: number): void;
    setLineJitterRadius(view_key: ViewKey, value: number): void;
    setLineJitterFrequency(view_key: ViewKey, value: number): void;
    /**
     * Unsets the visibility mask override for the given instances
     * @param instances Instances to apply the override to
     * @param viewIds Array of view IDs to remove override from. Pass empty array to remove from all views.
     */
    unsetElementsVisibilityOverride(instances: InstanceIncs, viewIds: number[]): void;
    /**
     * Sets the visibility mask override for the given instances
     * @param instances Instances to apply the override to
     * @param viewIds Array of view IDs to apply override to. Pass empty array to apply to all views.
     * @param pointsVisible if points should be visible in the mask
     * @param linesVisible if lines should be visible in the mask
     * @param facesVisible if faces should be visible in the mask
     */
    setElementsVisibilityOverride(instances: InstanceIncs, viewIds: number[], pointsVisible: boolean, linesVisible: boolean, facesVisible: boolean): void;
    /**
     * Unsets the draw mode override for the given instances
     * @param instances Instances to apply the override to
     * @param viewIds Array of view IDs to remove override from. Pass empty array to remove from all views.
     */
    unsetElementsDrawModeOverride(instances: InstanceIncs, viewIds: number[]): void;
    /**
     * Sets the draw mode override for the given instances
     * @param instances Instances to apply the override to
     * @param viewIds Array of view IDs to apply override to. Pass empty array to apply to all views.
     * @param mode The draw mode to apply
     */
    setElementsDrawModeOverride(instances: InstanceIncs, viewIds: number[], mode: ScDrawMode): void;
    get3dContext(): WebGLRenderingContext | WebGL2RenderingContext | null;
}
