import { IBox, Matrix12, Matrix9, IRay, Vector3, Vector4 } from '@ts3d-hoops/common';
import { ILight, LightSpace, LightType } from './lights';
import { LoadConfig } from './LoadConfig';
import { MeshInstanceInterface } from './MeshInstanceInterface';
import { OverlayInterface } from './overlays';
import { MatrixInterface } from './maths';
import { MeshDataInterface, MeshDataBuilder } from './meshdata';
import { AntiAliasingMode, AttachScope, BadDataData, BimType, BlurIntervalUnit, CuttingSectionLimits, DrawMode, DrawStrategy, ElementType, FrameStats, HighlightFilter, HighlightMode, OpenModelFailedData, PointShape, PointSizeUnit, SessionType, SetVisibility, SimpleReflectionAttenuationUnit, Statistics, TransparencyMode, ViewKey, XRayGroup, Milliseconds, ScModelName, ScsBuffer } from './misc';
import { ImageInterface } from './images';
import { CuttingSectionKey, DataIds, DataKey, GroupIds, ImageId, ImageIds, InclusionKey, InstanceIncs, InstanceKey, LightKey, MasterModelKey, MeshKey, ModelKey } from './keys';
import { SvgConfig } from './SvgConfig';
import { Camera } from './Camera';
import { RaySelectionConfig, VolumeSelectionConfig, IncrementalSelectionHandle } from './selections';
import { SsrQualityConfig } from './SsrQualityConfig';
import { PickResult } from './entities';
export interface Instance {
    MeshInstance: MeshInstanceInterface;
    Overlay: OverlayInterface;
    MeshDataBuilder: {
        new (): MeshDataBuilder;
    };
    MeshData: MeshDataInterface;
    Matrix: MatrixInterface;
    Image: ImageInterface;
    setEventHandler(eventName: 'announce_model', callback: (eventName: string, attachScope: AttachScope, masterModelKey: MasterModelKey) => void): void;
    setEventHandler(eventName: 'bad_data', callback: (eventName: string, data: BadDataData) => void): void;
    setEventHandler(eventName: 'bounding', callback: (eventName: string) => void): void;
    setEventHandler(eventName: 'camera_set', callback: (eventName: string, viewKey: ViewKey) => void): void;
    setEventHandler(eventName: 'capping_idle', callback: (eventName: string, isIdle: boolean, cappedInstanceCount: number) => void): void;
    setEventHandler(eventName: 'client_message', callback: (eventName: string, data: string) => void): void;
    setEventHandler(eventName: 'draw_complete', callback: (eventName: string, viewKey: ViewKey) => void): void;
    setEventHandler(eventName: 'draw_idle', callback: (eventName: string, viewKey: ViewKey) => void): void;
    setEventHandler(eventName: 'first_instance', callback: (eventName: string) => void): void;
    setEventHandler(eventName: 'inclusion', callback: (eventName: string, attachScope: AttachScope, inclusionKey: InclusionKey, modelKey: ModelKey) => void): void;
    setEventHandler(eventName: 'meta_data', callback: (eventName: string, modelKey: ModelKey, dataKey: DataKey, data: Uint8Array) => void): void;
    setEventHandler(eventName: 'missing_model', callback: (eventName: string, attachScope: AttachScope, modelPath: string) => void): void;
    setEventHandler(eventName: 'network_receive_data', callback: (eventName: string, dataSize: number) => void): void;
    setEventHandler(eventName: 'open_model_failed', callback: (eventName: string, data: OpenModelFailedData) => void): void;
    setEventHandler(eventName: 'post_draw', callback: (eventName: string, draw_index: ViewKey, stats: FrameStats, camera: Camera, visiblePoints: number[]) => void): void;
    setEventHandler(eventName: 'post_draw_json', callback: (eventName: string, metadataJson: string) => void): void;
    setEventHandler(eventName: 'priority_meta_data_sent', callback: (eventName: string, attachScope: AttachScope, prototypeInstanceCount: number) => void): void;
    setEventHandler(eventName: 'remap_inclusion', callback: (eventName: string, attachScope: AttachScope, effectiveModelKey: ModelKey, effectiveInclusionKey: InclusionKey, originalInclusionKey: InclusionKey) => void): void;
    setEventHandler(eventName: 'remap_model', callback: (eventName: string, attachScope: AttachScope, effectiveModelKey: ModelKey, originalModelKey: ModelKey) => void): void;
    setEventHandler(eventName: 'session_started', callback: (eventName: string, primaryModelKey: ModelKey) => void): void;
    setEventHandler(eventName: 'socket_error', callback: (eventName: string) => void): void;
    setEventHandler(eventName: 'socket_open_failed', callback: (eventName: string) => void): void;
    setEventHandler(eventName: 'stream_active', callback: (eventName: string) => void): void;
    setEventHandler(eventName: 'stream_idle', callback: (eventName: string) => void): void;
    setEventHandler(eventName: 'webgl_context_lost', callback: (eventName: string) => void): void;
    setEventHandler(eventName: 'websocket_connection_closed', callback: (eventName: string) => void): void;
    unsetEventHandler(eventName: 'announce_model', callback: (eventName: string, attachScope: AttachScope, modelKey: ModelKey) => void): void;
    unsetEventHandler(eventName: 'bad_data', callback: (eventName: string, data: BadDataData) => void): void;
    unsetEventHandler(eventName: 'bounding', callback: (eventName: string) => void): void;
    unsetEventHandler(eventName: 'camera_set', callback: (eventName: string, viewKey: ViewKey) => void): void;
    unsetEventHandler(eventName: 'capping_idle', callback: (eventName: string, isIdle: boolean, cappedInstanceCount: number) => void): void;
    unsetEventHandler(eventName: 'client_message', callback: (eventName: string, data: string) => void): void;
    unsetEventHandler(eventName: 'draw_complete', callback: (eventName: string, viewKey: ViewKey) => void): void;
    unsetEventHandler(eventName: 'draw_idle', callback: (eventName: string, viewKey: ViewKey) => void): void;
    unsetEventHandler(eventName: 'inclusion', callback: (eventName: string, attachScope: AttachScope, inclusionKey: InclusionKey, modelKey: ModelKey) => void): void;
    unsetEventHandler(eventName: 'meta_data', callback: (eventName: string, modelKey: ModelKey, dataKey: DataKey, data: Uint8Array) => void): void;
    unsetEventHandler(eventName: 'missing_model', callback: (eventName: string, attachScope: AttachScope, modelPath: string) => void): void;
    unsetEventHandler(eventName: 'network_receive_data', callback: (eventName: string, dataSize: number) => void): void;
    unsetEventHandler(eventName: 'open_model_failed', callback: (eventName: string, data: OpenModelFailedData) => void): void;
    unsetEventHandler(eventName: 'post_draw', callback: (eventName: string, draw_index: ViewKey, stats: FrameStats, camera: Camera, visiblePoints: number[]) => void): void;
    unsetEventHandler(eventName: 'post_draw_json', callback: (eventName: string, metadataJson: string) => void): void;
    unsetEventHandler(eventName: 'priority_meta_data_sent', callback: (eventName: string, attachScope: AttachScope, prototypeInstanceCount: number) => void): void;
    unsetEventHandler(eventName: 'remap_inclusion', callback: (eventName: string, attachScope: AttachScope, effectiveModelKey: ModelKey, effectiveInclusionKey: InclusionKey, originalInclusionKey: InclusionKey) => void): void;
    unsetEventHandler(eventName: 'remap_model', callback: (eventName: string, attachScope: AttachScope, effectiveModelKey: ModelKey, originalModelKey: ModelKey) => void): void;
    unsetEventHandler(eventName: 'session_started', callback: (eventName: string, primaryModelKey: ModelKey) => void): void;
    unsetEventHandler(eventName: 'socket_error', callback: (eventName: string) => void): void;
    unsetEventHandler(eventName: 'socket_open_failed', callback: (eventName: string) => void): void;
    unsetEventHandler(eventName: 'stream_active', callback: (eventName: string) => void): void;
    unsetEventHandler(eventName: 'stream_idle', callback: (eventName: string) => void): void;
    unsetEventHandler(eventName: 'webgl_context_lost', callback: (eventName: string) => void): void;
    unsetEventHandler(eventName: 'websocket_connection_closed', callback: (eventName: string) => void): void;
    allowHighDpi: boolean;
    containers: Map<ViewKey, Element>;
    wrappers: Map<ViewKey, HTMLDivElement>;
    canvas: OffscreenCanvas | HTMLCanvasElement;
    addCuttingSection(cuttingPlanes: Vector4[]): Promise<CuttingSectionKey>;
    addDrawContext(): Promise<ViewKey>;
    addLight(viewKey: ViewKey, type: LightType, space: LightSpace, position: Vector3, color: Vector3): Promise<LightKey>;
    setLightPower(viewKey: ViewKey, key: LightKey, power: number): void;
    setLightDecay(viewKey: ViewKey, key: LightKey, decay: number): void;
    advanceVolumeSelection(handle: IncrementalSelectionHandle, batchCapacity: number): Promise<InstanceIncs>;
    attachModels(attachScope: AttachScope, modelNameWithTransform: [ScModelName, Matrix12][], attachMeasurementUnit: number, attachInvisibly: boolean): Promise<void>;
    attachScsBuffer(attachScope: AttachScope, buffer: ScsBuffer, inclusionMatrix: Matrix12, attachMeasurementUnit: number, attachInvisibly: boolean, resolveOnFullyLoaded: boolean, cancelUnitMatrix: boolean, autoUnitScale: boolean): Promise<void>;
    feedScsBuffer(attachScope: AttachScope, buffer: ScsBuffer | null): void;
    attachScsModelByKey(attachScope: AttachScope, matrix: Matrix12, modelKey: ModelKey, attachMeasurementUnit: number, attachInvisibly: boolean): InclusionKey;
    beginConvexPolyhedronSelection(volumePlaneCoeffs: Vector4[], heuristicOrigin: Vector3, config: VolumeSelectionConfig, viewKey: ViewKey): Promise<IncrementalSelectionHandle>;
    beginRayDrillSelection(viewKey: ViewKey, rayCssOriginX: number, rayCssOriginY: number, rayCssBoxRadius: number, config: VolumeSelectionConfig): Promise<IncrementalSelectionHandle>;
    beginScreenAreaSelection(viewKey: ViewKey, areaCssMinX: number, areaCssMinY: number, areaCssMaxX: number, areaCssMaxY: number, config: VolumeSelectionConfig): Promise<IncrementalSelectionHandle>;
    beginSphereSelection(viewKey: ViewKey, sphereCenter: Vector3, sphereRadius: number, config: VolumeSelectionConfig): Promise<IncrementalSelectionHandle>;
    clearLights(viewKey: ViewKey): void;
    cuttingSectionLimits(): CuttingSectionLimits;
    debug_log(message: string): Promise<void>;
    debug_stateFailure(stateFailureValue: number): Promise<void>;
    Debug_sync(): Promise<void>;
    demandMeshInstances(incs: InstanceIncs): void;
    detachInclusions(inclusionKeys: InclusionKey[]): Promise<void>;
    disableCapping(viewKey: ViewKey): void;
    disconnectNetwork(): void;
    enableCapping(viewKey: ViewKey, lineColor: Vector4, faceColor: Vector4, quantizationGranularity: number): void;
    endComparison(viewKey: ViewKey): void;
    endVolumeSelection(handle: IncrementalSelectionHandle): void;
    explode(distance: number): void;
    createFloorplanMesh(incs: InstanceIncs): Promise<InstanceIncs>;
    exportToSvg(config: SvgConfig): Promise<number[]>;
    beginExportToSvg(config: SvgConfig): Promise<void>;
    advanceExportToSvg(): Promise<number[]>;
    flushMetaDataCache(): void;
    getAmbientOcclusionEnabled(viewKey: ViewKey): Promise<boolean>;
    getAmbientOcclusionRadius(viewKey: ViewKey): Promise<number>;
    getBackFacesVisible(viewKey: ViewKey): Promise<boolean>;
    getBackgroundGradient(viewKey: ViewKey): Promise<[Vector4, Vector4]>;
    getCamera(viewKey: ViewKey): Camera;
    getCameraPromise(viewKey: ViewKey): Promise<Camera>;
    getCappedInstances(): Promise<InstanceIncs>;
    getCuttingSections(sectionKeys: CuttingSectionKey[]): Promise<Vector4[]>;
    getDefaultDepthRange(viewKey: ViewKey): Promise<Range>;
    getElementCount(): Promise<number>;
    getEyeDomeLightingBlurEdgeDistance(viewKey: ViewKey): Promise<number>;
    getEyeDomeLightingBlurInterval(viewKey: ViewKey): Promise<number>;
    getEyeDomeLightingBlurSamples(viewKey: ViewKey): Promise<number>;
    getEyeDomeLightingEnabled(viewKey: ViewKey): Promise<boolean>;
    getEyeDomeLightingOpacity(viewKey: ViewKey): Promise<number>;
    getEyeDomeLightingShadingEdgeDistance(viewKey: ViewKey): Promise<number>;
    getFacesVisible(viewKey: ViewKey): Promise<boolean>;
    getFaceWindingFlipped(viewKey: ViewKey): Promise<boolean>;
    getFrontFacesVisible(viewKey: ViewKey): Promise<boolean>;
    getInteractiveDrawLimitIncreaseEnabled(viewKey: ViewKey): Promise<boolean>;
    getLightKeys(viewKey: ViewKey): Promise<LightKey[]>;
    getLight(viewKey: ViewKey, key: LightKey): Promise<ILight>;
    getLinesVisible(viewKey: ViewKey): Promise<boolean>;
    getLooseBounding(): Promise<IBox>;
    getMetaData(ids: DataIds): Promise<Uint8Array[]>;
    getMinFrameRate(viewKey: ViewKey): Promise<number>;
    getNetworkVersion(): number;
    getPointShape(viewKey: ViewKey): Promise<PointShape>;
    getPointSize(viewKey: ViewKey): Promise<number>;
    getPointSizeUnit(viewKey: ViewKey): Promise<PointSizeUnit>;
    getPointsVisible(viewKey: ViewKey): Promise<boolean>;
    getStatistics(): Promise<Statistics>;
    getStreamedBounding(): Promise<IBox>;
    getStreamVersion(): number;
    getTriangleCount(): Promise<number>;
    load(configuration: LoadConfig): SessionType;
    markAllMeshInstancesInteresting(interesting: boolean): void;
    markCameraAsEmpty(viewKey: ViewKey): void;
    meshInstanceKeyInfo(modelKeyOrAttachScope: ModelKey | AttachScope, byModel: boolean, keyCountOnly: boolean): Promise<(ModelKey | InstanceKey)[] | [number]>;
    metaDataKeyInfo(modelKeyOrAttachScope: ModelKey | AttachScope, byModel: boolean, keyCountOnly: boolean): Promise<(ModelKey | DataKey)[] | [number]>;
    modelKeysFromInclusionKeys(inclusionKeys: InclusionKey[]): Promise<ModelKey[]>;
    onResize(viewKey: ViewKey): void;
    pauseCapping(): void;
    primaryModelKey(): Promise<ModelKey>;
    queueRedraw(viewKey: ViewKey): void;
    registerBimInstances(incs: InstanceIncs, bimType: BimType): void;
    removeAllCuttingSections(): void;
    removeCuttingSections(sectionHandles: CuttingSectionKey[]): Promise<void>;
    removeDrawContext(viewKey: ViewKey): void;
    removeLight(viewKey: ViewKey, key: LightKey): void;
    replaceCuttingSection(cuttingPlanes: Vector4[], key: CuttingSectionKey): Promise<void>;
    requestGroups(groupIds: GroupIds, obtainDependentGroups: boolean): Promise<void>;
    requestImages(imageIds: ImageIds, wantThumbnails: boolean): Promise<void>;
    requestMeshInstances(incs: InstanceIncs, withMeshData: boolean, ignoreFailure: boolean): Promise<void>;
    requestMeshInstancesByGroup(groupId: GroupIds, withMeshData: boolean, expandGroups: boolean): Promise<void>;
    resetExplode(): void;
    resetToEmpty(whitelistInstances: InstanceKey[], whitelistMeshes: MeshKey[]): Promise<void>;
    resumeCapping(): void;
    resumeDrawing(viewKey: ViewKey): void;
    screenSelectByRay(viewKey: ViewKey, elementMask: number, canvasX: number, canvasY: number, maxPixelTolerance: number, config: RaySelectionConfig): Promise<PickResult>;
    serverSideRendering(): boolean;
    setAmbientLightColor(viewKey: ViewKey, value: Vector3): void;
    setAmbientOcclusionBias(viewKey: ViewKey, bias: number): void;
    setAmbientOcclusionBlurInterval(viewKey: ViewKey, interval: number): void;
    setAmbientOcclusionBlurSamples(viewKey: ViewKey, samples: number): void;
    setAmbientOcclusionContrast(viewKey: ViewKey, contrast: number): void;
    setAmbientOcclusionEdgeDistance(viewKey: ViewKey, distance: number): void;
    setAmbientOcclusionEnabled(viewKey: ViewKey, enabled: boolean): void;
    setAmbientOcclusionIntensity(viewKey: ViewKey, intensity: number): void;
    setAmbientOcclusionNoiseSize(viewKey: ViewKey, size: number): void;
    setAmbientOcclusionOpacity(viewKey: ViewKey, opacity: number): void;
    setAmbientOcclusionRadius(viewKey: ViewKey, radius: number): void;
    setAmbientOcclusionSamples(viewKey: ViewKey, samples: number): void;
    setAntiAliasingMode(viewKey: ViewKey, antiAliasingMode: AntiAliasingMode): void;
    setBackFacesVisible(viewKey: ViewKey, visible: boolean): void;
    setBackgroundColor(viewKey: ViewKey, color: Vector4): void;
    setBackgroundGradient(viewKey: ViewKey, top: Vector4, bottom: Vector4): void;
    setBloomBlurInterval(viewKey: ViewKey, layer: number, value: number, unit: BlurIntervalUnit): void;
    setBloomBlurSamples(viewKey: ViewKey, layer: number, value: number): void;
    setBloomEnabled(viewKey: ViewKey, value: boolean): void;
    setBloomIntensity(viewKey: ViewKey, layer: number, value: number): void;
    setBloomIntensityScale(viewKey: ViewKey, value: number): void;
    setBloomLayerCount(viewKey: ViewKey, value: number): void;
    setBloomThreshold(viewKey: ViewKey, value: number): void;
    setBloomThresholdRampWidth(viewKey: ViewKey, value: number): void;
    setBoundingPreviewUnderdrawColor(viewKey: ViewKey, color: Vector4): void;
    setBoundingPreviewTestedColor(viewKey: ViewKey, color: Vector4): void;
    setBoundingPreviewEjectedColor(viewKey: ViewKey, color: Vector4): void;
    setBoundingPreviewColor(viewKey: ViewKey, color: Vector4): void;
    setBoundingPreviewUnderdraw(points: Vector3[], viewKey: ViewKey): void;
    setBoundingPreviewTested(points: Vector3[], viewKey: ViewKey): void;
    setBoundingPreviewEjected(points: Vector3[], viewKey: ViewKey): void;
    setBoundingDebugLevel(viewKey: ViewKey, level: number): void;
    setCamera(viewKey: ViewKey, camera: Camera): void;
    setCappingIdleHookEnabled(enable: boolean): Promise<boolean>;
    setClumpingEnabled(value: boolean): void;
    setComparisonColors(viewKey: ViewKey, sameColor: Vector3, only1Color: Vector3, only2Color: Vector3): void;
    setCurrentView(viewKey: ViewKey, view: ViewKey): void;
    setDefaultDepthRange(viewKey: ViewKey, min: number, max: number): void;
    setDefaultGloss(viewKey: ViewKey, gloss: number): void;
    setDefaultMirror(viewKey: ViewKey, mirror: number): void;
    setDefaultSpecularMix(viewKey: ViewKey, mix: number): void;
    setDefaultSphereMap(viewKey: ViewKey, imageId: ImageId): void;
    setDisplayIncompleteFrames(viewKey: ViewKey, value: boolean): void;
    setDrawIdleDelay(viewKey: ViewKey, delay: number): void;
    setDrawMode(viewKey: ViewKey, drawMode: DrawMode): void;
    setDrawStrategy(viewKey: ViewKey, strategy: DrawStrategy): void;
    setEyeDomeLightingBlurEdgeDistance(viewKey: ViewKey, value: number): void;
    setEyeDomeLightingBlurInterval(viewKey: ViewKey, value: number): void;
    setEyeDomeLightingBlurSamples(viewKey: ViewKey, value: number): void;
    setEyeDomeLightingEnabled(viewKey: ViewKey, enabled: boolean): void;
    setEyeDomeLightingOpacity(viewKey: ViewKey, value: number): void;
    setEyeDomeLightingShadingEdgeDistance(viewKey: ViewKey, value: number): void;
    setFacesVisible(viewKey: ViewKey, visible: boolean): void;
    setFaceWindingFlipped(viewKey: ViewKey, flipped: boolean): void;
    setFixedDrawLimit(viewKey: ViewKey, value: number): void;
    setFrontFacesVisible(viewKey: ViewKey, visible: boolean): void;
    setGoochBaseColorProminence(viewKey: ViewKey, prominence: number): void;
    setGoochBlue(viewKey: ViewKey, blue: number): void;
    setGoochLuminanceShiftStrength(viewKey: ViewKey, shiftStrength: number): void;
    setGoochYellow(viewKey: ViewKey, yellow: number): void;
    setGroundPlane(viewKey: ViewKey, normal: Vector3): void;
    setGroundPlaneWithPosition(viewKey: ViewKey, normal: Vector3, position?: Vector3): void;
    setHardEdgeColor(viewKey: ViewKey, value: Vector3): void;
    setHardEdgeOpacity(viewKey: ViewKey, value: number): void;
    setHardEdgesEnabled(viewKey: ViewKey, value: boolean): void;
    setHardEdgeThreshold(viewKey: ViewKey, value: number): void;
    setHardEdgeThresholdRampWidth(viewKey: ViewKey, value: number): void;
    setHiddenLineHiddenLineColor(viewKey: ViewKey, color: Vector4): void;
    setHiddenLineHighlightedElementFillColor(viewKey: ViewKey, color: Vector4): void;
    setHiddenLineHighlightedElementOutlineColor(viewKey: ViewKey, color: Vector4): void;
    setHiddenLineHighlightedInstanceFillColor(viewKey: ViewKey, color: Vector4): void;
    setHiddenLineHighlightedInstanceOutlineColor(viewKey: ViewKey, color: Vector4): void;
    setHiddenLineVisibleLineColor(viewKey: ViewKey, color: Vector4): void;
    setHighlightColorizeCompression(viewKey: ViewKey, compressionLevel: number): void;
    setHighlightedElementColor(viewKey: ViewKey, color: Vector4): void;
    setHighlightedElementFilter(viewKey: ViewKey, highlightedFilter: HighlightFilter): void;
    setHighlightedElementOutlineColor(viewKey: ViewKey, highlightedOutlineColor: Vector4): void;
    setHighlightedInstanceColor(viewKey: ViewKey, color: Vector4): void;
    setHighlightedInstanceFilter(viewKey: ViewKey, highlightedFilter: HighlightFilter): void;
    setHighlightedInstanceOutlineColor(viewKey: ViewKey, highlightedOutlineColor: Vector4): void;
    setHighlightMode(viewKey: ViewKey, highlightMode: HighlightMode): void;
    setImageBasedLightingEnabled(viewKey: ViewKey, value: boolean): void;
    setImageBasedLightingEnvironment(viewKey: ViewKey, data: Uint8Array): void;
    setImageBasedLightingEnvironmentToDefault(viewKey: ViewKey): void;
    setImageBasedLightingIntensity(viewKey: ViewKey, value: number): void;
    setImageBasedLightingMatrix(viewKey: ViewKey, value: Matrix9): void;
    setInstancingEnabled(viewKey: ViewKey, value: boolean): void;
    setInteractiveDrawLimitIncreaseEnabled(viewKey: ViewKey, enable: boolean): void;
    setInteractiveDrawLimitIncreaseInterval(viewKey: ViewKey, milliseconds: number): void;
    setLightingEnabled(viewKey: ViewKey, enabled: boolean): void;
    setLineJitterEnabled(viewKey: ViewKey, enabled: boolean): void;
    setLineJitterFrequency(viewKey: ViewKey, value: number): void;
    setLineJitterInstanceCount(viewKey: ViewKey, value: number): void;
    setLineJitterRadius(viewKey: ViewKey, value: number): void;
    setLinesVisible(viewKey: ViewKey, visible: boolean): void;
    setMeshLevel(incs: InstanceIncs, level: number): void;
    setMetallicRoughnessMaterialOverride(defaultMetallicFactor: number, defaultRoughnessFactor: number): void;
    setMinDrawLimit(viewKey: ViewKey, value: number): void;
    setMinFrameRate(viewKey: ViewKey, value: number): void;
    setMinIncrementalFrameRate(viewKey: ViewKey, value: number): void;
    setMinInteractiveFrameRate(viewKey: ViewKey, value: number): void;
    setPointShape(viewKey: ViewKey, shape: PointShape): void;
    setPointSize(viewKey: ViewKey, size: number, unit: PointSizeUnit): void;
    setPointsVisible(viewKey: ViewKey, visible: boolean): void;
    setPointVisibilityTest(points: Vector3[], viewKey: ViewKey): void;
    setPostInputDelay(viewKey: ViewKey, value: number): void;
    setSilhouetteColor(viewKey: ViewKey, value: Vector3): void;
    setSilhouetteEnabled(viewKey: ViewKey, value: boolean): void;
    setSilhouetteOpacity(viewKey: ViewKey, value: number): void;
    setSilhouetteThreshold(viewKey: ViewKey, value: number): void;
    setSilhouetteThresholdRampWidth(viewKey: ViewKey, value: number): void;
    setSimpleReflectionAttenuation(viewKey: ViewKey, nearDistance: number, farDistance: number, unit: SimpleReflectionAttenuationUnit): void;
    setSimpleReflectionBlurInterval(viewKey: ViewKey, value: number, unit: BlurIntervalUnit): void;
    setSimpleReflectionBlurSamples(viewKey: ViewKey, value: number): void;
    setSimpleReflectionEnabled(viewKey: ViewKey, value: boolean): void;
    setSimpleReflectionFadeAngle(viewKey: ViewKey, degrees: number): void;
    setSimpleReflectionOpacity(viewKey: ViewKey, value: number): void;
    setSimpleShadowBlurInterval(viewKey: ViewKey, value: number): void;
    setSimpleShadowBlurSamples(viewKey: ViewKey, value: number): void;
    setSimpleShadowColor(viewKey: ViewKey, value: Vector3): void;
    setSimpleShadowEnabled(viewKey: ViewKey, value: boolean): void;
    setSimpleShadowInteractiveUpdateEnabled(viewKey: ViewKey, value: boolean): void;
    setSimpleShadowOpacity(viewKey: ViewKey, value: number): void;
    setSimpleShadowResolution(viewKey: ViewKey, pixels: number): void;
    setSsrQuality(opts: SsrQualityConfig): void;
    setStreamCutoffScale(value: number): void;
    setStreamIdleMarker(): Promise<void>;
    setToonBandCount(viewKey: ViewKey, bandCount: number): void;
    setToonSpecularFactor(viewKey: ViewKey, specularFactor: number): void;
    setTransparencyMode(viewKey: ViewKey, value: TransparencyMode): void;
    setUnhighlightedColor(viewKey: ViewKey, color: Vector4): void;
    setUnhighlightedFilter(viewKey: ViewKey, highlightedFilter: HighlightFilter): void;
    setVisibilityByAttachment(attachScope: AttachScope, setVisibility: SetVisibility): void;
    setXRayMaterial(viewKey: ViewKey, group: XRayGroup, element: ElementType, color: Vector4): void;
    setXRayOpacity(viewKey: ViewKey, element: ElementType, value: number): void;
    setXRayTransparencyMode(viewKey: ViewKey, value: TransparencyMode): void;
    shutDown(): void;
    startComparison(viewKey: ViewKey, instanceSet1: InstanceIncs, instanceSet2: InstanceIncs): void;
    startExplode(incs: InstanceIncs, center: Vector3): void;
    suspendDrawing(viewKey: ViewKey): void;
    testPointVisibility(points: Vector3[], viewKey: ViewKey): Promise<number[]>;
    throttleLoad(newPauseInterval: Milliseconds, throttleDuration: Milliseconds): void;
    triangulatePolygon(polygonPoints: Float32Array | number[], normal: Vector3): number[];
    truncateMetaData(dataIds: DataIds): Promise<void>;
    unsetAllColors(): void;
    unsetAllHighlighted(): void;
    unsetAllOpacity(): void;
    unsetAllXRay(): void;
    unsetCurrentView(viewKey: ViewKey): void;
    unsetXRayMaterial(viewKey: ViewKey, group: XRayGroup, element: ElementType): Promise<void>;
    updateLight(viewKey: ViewKey, key: LightKey, type: LightType, space: LightSpace, position: Vector3, color: Vector3): void;
    waitForImageDecoding(): Promise<void>;
    worldSelectByRay(viewKey: ViewKey, ray: IRay, config: RaySelectionConfig): Promise<PickResult>;
    getGLContext(): WebGL2RenderingContext | WebGLRenderingContext | null;
    _loseWebGlContext(): boolean;
}
