import { Point2 } from '@ts3d-hoops/common';
import { MarkupRenderer } from '../MarkupRenderer';
import { Circle, CircleCollection } from '../shapes/Circle';
import { Line, LineCollection } from '../shapes/Line';
import { Polygon, PolygonCollection } from '../shapes/Polygon';
import { Polyline, PolylineCollection } from '../shapes/Polyline';
import { Rectangle, RectangleCollection } from '../shapes/Rectangle';
import { TextCollection, TextMarkupBase, Text } from '../shapes/Text';
import { TextBox, TextBoxCollection } from '../shapes/TextBox';
export declare class SVGMarkupRenderer implements MarkupRenderer {
    private _svgCanvas;
    private _svgDefsElement;
    private _svgElements;
    private _svgTextElements;
    _setCanvas(canvas: Element): void;
    _clear(): void;
    _finalize(): void;
    drawCircle(circle: Circle): Element;
    drawCircles(circleCollection: CircleCollection): Element[];
    drawLine(line: Line): SVGLineElement;
    drawLines(lineCollection: LineCollection): Element[];
    drawText(text: Text): SVGTextContentElement;
    drawTexts(texts: TextCollection): Element[];
    measureText(str: string, text: TextMarkupBase): Point2;
    measureTextBox(textBox: TextBox): Point2;
    drawPolyline(line: Polyline): SVGPolylineElement;
    drawPolylines(polylineCollection: PolylineCollection): Element[];
    drawPolygon(polygon: Polygon): Element;
    drawPolygons(polygonCollection: PolygonCollection): Element[];
    drawRectangle(rectangle: Rectangle): Element;
    drawRectangles(rectangleCollection: RectangleCollection): Element[];
    drawTextBox(textBox: TextBox): Element[];
    drawTextBoxes(textBoxes: TextBoxCollection): Element[][];
    private _addTextBoxElement;
    private _renderEndcaps;
    private _createTextElement;
    private _addTextElement;
    private _addRectangleElement;
    private _addLineElement;
    private _addPolygonElement;
    private _addPolylineElement;
    private _addCircleNode;
    private _setGenericFillAttributes;
    private _setGenericStrokeAttributes;
    private _addSVGTextItemElement;
    private _addSVGElement;
}
