import { Plane, Matrix16 } from '@ts3d-hoops/common';
import { Camera } from '../../../Camera';
import { AuthoredNodeId, RuntimeNodeId } from '../NodeId';
import { ProductOccurrence } from './ProductOccurrence';
import { AbstractCuttingManager } from '../AbstractCore';
import { CadViewBits, CadViewInfo } from './types';
import { NodeMixin } from './NodeMixin';
import { ViewFrame } from './ViewFrame';
import { BranchVisibility, FilterId, LoadSubtreeConfig } from '../../../types';
import { Pmi } from './Pmi';
import { InclusionContext } from '../context/InclusionContext';
import { AssemblyDataParser } from '../load/AssemblyDataParser';
import { PhantomMember } from '../../types';
import { IScEngine } from '../../../core/IScEngine';
import { ICallbackManager } from '../../../core/ICallbackManager';
import { IAssemblyTree, IView } from '../../../core';
export type CadViewParent = ProductOccurrence;
export declare class CadView extends NodeMixin<CadViewBits> {
    static parseXml(assemblyTree: IAssemblyTree, elem: Element, inclusionContext: InclusionContext, config: LoadSubtreeConfig): CadViewInfo<AuthoredNodeId>;
    static parseBinary(assemblyTree: IAssemblyTree, inclusionContext: InclusionContext, parser: AssemblyDataParser, config: LoadSubtreeConfig): CadViewInfo<AuthoredNodeId>;
    static reify(assemblyTree: IAssemblyTree, inclusionContext: InclusionContext, info: CadViewInfo<AuthoredNodeId>, parent: CadViewParent): CadView;
    static createDynamic(assemblyTree: IAssemblyTree, parent: CadViewParent, name: string, camera: Camera, pmis: Pmi[] | null, productOccurrencesToShow: RuntimeNodeId[], productOccurrencesToHide: RuntimeNodeId[], transformMap: Map<RuntimeNodeId, Matrix16>, cuttingPlane: Plane | null): CadView;
    private static isAuthoredViewInfo;
    private constructor();
    getFilters(): FilterId[] | null;
    private static _toRuntimeIds;
    private _loadViewFrame;
    getViewFrame(): ViewFrame | null;
    getParent(): CadViewParent;
    getRuntimeId(): RuntimeNodeId;
    getBranchVisibility(): BranchVisibility;
    setVisibility(visible: boolean): void;
    isPmiFilteringSet(): boolean;
    isDefaultView(): boolean;
    IsCombineState(): boolean;
    deactivate(cuttingManager: AbstractCuttingManager): Promise<void>;
    private _replaceCuttingPlanes;
    activate(assemblyTree: IAssemblyTree, engine: IScEngine, callbackManager: ICallbackManager, cuttingManager: AbstractCuttingManager, view: IView, duration: number, massageCamera: boolean, configurationNode: ProductOccurrence | null): Promise<void>;
    private _activateView;
    private _activateCamera;
    hasPmi(pmi: Pmi): boolean;
    isAnnotationView(): boolean;
    isCombineStateView(): boolean;
    setViewFrame(viewFrame: ViewFrame): void;
    protected readonly __CadView: PhantomMember;
    private readonly _parent;
    private readonly _camera;
    private readonly _instanceMarkupKeysToShow;
    private readonly _nodesToShow;
    private readonly _nodesToHide;
    private readonly _filters;
    private _viewFrame;
    private readonly _transformMap;
    private readonly _cuttingPlanes;
}
