import { Point2, Matrix, Point3 } from '@ts3d-hoops/common';
import { AttachScope, DataKey, InclusionKey, InstanceInc, MasterModelKey, ModelKey, ViewKey } from '@ts3d-hoops/streamcache';
import { Camera } from '../Camera';
import { AttachType } from './types';
import { MeasureMarkup } from '../operators/markup/measure/MeasureMarkup';
import { NoteText } from '../operators/markup/note/NoteText';
import { BodyId, CadViewId, NodeId, OverlayIndex, SheetId, EventType, FileType, HandleEventType, InfoType, KeyModifiers, NodeSource, ScModelName, ViewOrientation, LoadSubtreeConfig } from '../types';
import { CallbackMap } from '../CallbackMap';
import { AssemblyDataHeader } from './tree/AssemblyData';
import { MarkupView } from '../markup/MarkupView';
import { LineMarkup } from '../markup/line/LineMarkup';
import { RedlineItem } from '../markup/redline/RedlineItem';
import { BCFName } from '../bcf';
import { InputEvent } from '../event/InputEvent';
import { NodeSelectionEvent } from '../event/SelectionEvent';
import { IView } from '../core/IView';
import { ICallbackManager } from '../core/ICallbackManager';
import { ICuttingSection } from '../core';
export declare class CallbackManager implements ICallbackManager {
    private readonly _aliasMap;
    private readonly _callbackMap;
    private _activeTriggerDepth;
    private readonly _pendingClearUnboundFilteredNames;
    constructor();
    private _filterName;
    bind(callbackMap: CallbackMap, highPriority?: boolean): void;
    unbind(callbackMap: CallbackMap): void;
    private _clearUnboundCallbacks;
    promiseTrigger(name: '_assemblyTreeReady', delegate: 'assemblyTreeReady'): Promise<void>;
    promiseTrigger(name: '_firstAttachment', delegate: null, attachType: AttachType): Promise<void>;
    promiseTrigger(name: '_firstBoundingReady', delegate: null): Promise<void>;
    promiseTrigger(name: '_firstModelLoaded', delegate: 'firstModelLoaded', modelRootIds: NodeId[], isHwf: boolean, attachType: AttachType, config: LoadSubtreeConfig): Promise<void>;
    promiseTrigger(name: '_modelStructureHeaderParsed', delegate: null, header: AssemblyDataHeader): Promise<void>;
    promiseTrigger(name: '_modelStructureReady', delegate: 'modelStructureReady'): Promise<void>;
    promiseTrigger(name: '_modelSwitched', delegate: 'modelSwitched', clearOnly: boolean, newRoots: NodeId[], attachType: AttachType): Promise<void>;
    promiseTrigger(name: '_resetAssemblyTreeBegin', delegate: null): Promise<void>;
    promiseTrigger(name: '_resetDrawing', delegate: null): Promise<void>;
    promiseTrigger(name: '_sessionStarted', delegate: null): Promise<void>;
    promiseTrigger(name: '_subtreeLoaded', delegate: 'subtreeLoaded', loadedRootIds: NodeId[], source: NodeSource): Promise<void>;
    private _unsafePromiseTrigger;
    trigger(name: '_announceModel', attachScope: AttachScope, masterModelKey: MasterModelKey): void;
    trigger(name: '_attached', attachScope: AttachScope): void;
    trigger(name: '_attachmentPopulated', rootIds: NodeId[]): void;
    trigger(name: '_drawComplete', viewKey: ViewKey): void;
    trigger(name: '_firstInstance'): void;
    trigger(name: '_geometryCreated', inc: InstanceInc): void;
    trigger(name: '_inclusion', attachScope: AttachScope, inclusionKey: InclusionKey, modelKey: ModelKey): void;
    trigger(name: '_inputInteraction', event: InputEvent, eventType: EventType): void;
    trigger(name: '_metaData', modelKey: ModelKey, dataKey: DataKey, data: Uint8Array): void;
    trigger(name: '_missingModel', attachScope: AttachScope, modelPath: string): void;
    trigger(name: '_priorityMetaDataSent', attachScope: AttachScope, prototypeInstanceCount: number): void;
    trigger(name: '_remapInclusion', attachScope: AttachScope, effectiveModelKey: ModelKey, effectiveInclusionKey: InclusionKey, originalInclusionKey: InclusionKey): void;
    trigger(name: '_remapModel', attachScope: AttachScope, effectiveModelKey: ModelKey, originalModelKey: ModelKey): void;
    trigger(name: '_fetchBegin', url: string, attachScope: AttachScope): void;
    trigger(name: '_fetchEnd', url: string, attachScope: AttachScope): void;
    trigger(name: '_resetOpacity'): void;
    trigger(name: '_rootModelKey', modelKey: ModelKey): void;
    trigger(name: '_shutdownBegin'): void;
    trigger(name: '_test'): void;
    trigger(name: '_timeout'): void;
    trigger(name: '_updateTransform', isFullyOutOfHierarchy: boolean): void;
    trigger(name: '_drawContextCreated', key: ViewKey): void;
    trigger(name: '_drawContextDestroyed', key: ViewKey): void;
    trigger(name: 'addCuttingSection', cuttingSection: ICuttingSection): void;
    trigger(name: 'bcfLoaded', id: number, filename: BCFName): void;
    trigger(name: 'bcfRemoved', id: number): void;
    trigger(name: 'beginInteraction', view: IView): void;
    trigger(name: 'cadViewCreated', cadViewId: CadViewId, cadViewName: string): void;
    trigger(name: 'camera', camera: Camera, view: IView): void;
    trigger(name: 'cappingIdle', isIdle: boolean, cappedInstanceCount: number): void;
    trigger(name: 'configurationActivated', id: NodeId): void;
    trigger(name: 'contextMenu', position: Point2, modifiers: KeyModifiers): void;
    trigger(name: 'cuttingPlaneDragStart', cuttingSection: ICuttingSection, planeIndex: number): void;
    trigger(name: 'cuttingPlaneDrag', cuttingSection: ICuttingSection, planeIndex: number): void;
    trigger(name: 'cuttingPlaneDragEnd', cuttingSection: ICuttingSection, planeIndex: number): void;
    trigger(name: 'cuttingSectionsLoaded'): void;
    trigger(name: 'endInteraction', view: IView): void;
    trigger(name: 'explode', magnitude: number): void;
    trigger(name: 'frameDrawn', camera: Camera, visiblePoints: number[], viewKey: ViewKey): void;
    trigger(name: 'handleEvent', eventType: HandleEventType, nodeIds: NodeId[], initialMatrices: Matrix[], newMatrices: Matrix[]): void;
    trigger(name: 'handleEventEnd', eventType: HandleEventType, nodeIds: NodeId[], initialMatrices: Matrix[], newMatrices: Matrix[]): void;
    trigger(name: 'handleEventStart', eventType: HandleEventType, nodeIds: NodeId[], initialMatrices: Matrix[]): void;
    trigger(name: 'hwfParseComplete'): void;
    trigger(name: 'incrementalSelectionBatchBegin'): void;
    trigger(name: 'incrementalSelectionBatchEnd'): void;
    trigger(name: 'incrementalSelectionEnd'): void;
    trigger(name: 'info', infoType: InfoType, message: string): void;
    trigger(name: 'lineCreated', line: LineMarkup): void;
    trigger(name: 'lineDeleted', line: LineMarkup): void;
    trigger(name: 'lineLoaded', line: LineMarkup): void;
    trigger(name: 'measurementBegin'): void;
    trigger(name: 'measurementCreated', measurement: MeasureMarkup): void;
    trigger(name: 'measurementDeleted', measurement: MeasureMarkup): void;
    trigger(name: 'measurementHidden', measurement: MeasureMarkup): void;
    trigger(name: 'measurementLoaded', measurement: MeasureMarkup): void;
    trigger(name: 'measurementShown', measurement: MeasureMarkup): void;
    trigger(name: 'measurementValueSet', measurement: MeasureMarkup): void;
    trigger(name: 'missingModel', modelPath: string): void;
    trigger(name: 'modelLoadBegin'): void;
    trigger(name: 'modelLoadFailure', modelName: ScModelName, reason: string, exception?: any): void;
    trigger(name: 'modelStructureHeaderParsed', filename: string, fileType: FileType): void;
    trigger(name: 'modelSwitched', clearOnly: boolean, newRoots: NodeId[]): void;
    trigger(name: 'modelSwitchStart', clearOnly: boolean): void;
    trigger(name: 'noteTextCreated', noteText: NoteText): void;
    trigger(name: 'noteTextDeleted', noteText: NoteText): void;
    trigger(name: 'noteTextUpdated', noteText: NoteText): void;
    trigger(name: 'noteTextHidden', noteText: NoteText): void;
    trigger(name: 'noteTextShown', noteText: NoteText): void;
    trigger(name: 'overlayViewportSet', overlayIndex: OverlayIndex, view: IView): void;
    trigger(name: 'redlineCreated', redlineMarkup: RedlineItem): void;
    trigger(name: 'redlineDeleted', redlineMarkup: RedlineItem): void;
    trigger(name: 'redlineUpdated', redlineMarkup: RedlineItem): void;
    trigger(name: 'removeCuttingSection'): void;
    trigger(name: 'sceneReady'): void;
    trigger(name: 'selectionArray', events: NodeSelectionEvent[], removed: boolean): void;
    trigger(name: 'sheetActivated', id: SheetId): void;
    trigger(name: 'sheetDeactivated'): void;
    trigger(name: 'streamingActivated'): void;
    trigger(name: 'streamingDeactivated'): void;
    trigger(name: 'subtreeDeleted', loadedRootIds: NodeId[]): void;
    trigger(name: 'timeout'): void;
    trigger(name: 'timeoutWarning', warningTime: number): void;
    trigger(name: 'transitionBegin', duration: number, view: IView): void;
    trigger(name: 'transitionEnd', view: IView): void;
    trigger(name: 'viewAxes', frontVector: Point3, upVector: Point3): void;
    trigger(name: 'viewCreated', view: MarkupView): void;
    trigger(name: 'viewDeactivated', view: MarkupView): void;
    trigger(name: 'viewDeleted', view: MarkupView): void;
    trigger(name: 'viewLoaded', view: MarkupView): void;
    trigger(name: 'viewOrientation', orientation: ViewOrientation, view: IView): void;
    trigger(name: 'visibilityChanged', shownBodyIds: BodyId[], hiddenBodyIds: BodyId[]): void;
    trigger(name: 'walkOperatorActivated'): void;
    trigger(name: 'webGlContextLost'): void;
    trigger(name: 'websocketConnectionClosed'): void;
    trigger(name: 'XHRonerror', event: ErrorEvent): void;
    trigger(name: 'XHRonloadend', event: ProgressEvent, status: number, uri: string): void;
    trigger(name: 'XHRonprogress', event: ProgressEvent): void;
    unsafeTrigger(eventName: keyof CallbackMap, args?: any[]): void;
}
