import { EventDispatcher } from './EventDispatcher';
import { TimeoutMonitor } from './TimeoutMonitor';
import { ViewKey } from '@ts3d-hoops/streamcache';
export interface Options {
    usePointerEvents?: boolean;
}
export declare class InputMonitor {
    private static _activeEventDispatcher;
    private static _activeEventDispatcherLocked;
    private static _activeOffset;
    private readonly _eventDispatcher;
    private readonly _timeoutMonitor;
    private _viewKey;
    private readonly _isIE;
    private readonly _isFirefox;
    private _canvas;
    private _document;
    private _canvasEventFunctions;
    private _documentEventFunctions;
    private _pointerEventsEnabled;
    private _processInput;
    private _eventsBound;
    private _dragStarted;
    private _captureInput;
    private readonly _elementOffset;
    private _pointerUp;
    private _buttons;
    constructor(viewKey: ViewKey, eventDispatcher: EventDispatcher, timeoutMonitor: TimeoutMonitor);
    private _tryLockEventDispatcher;
    private _unlockEventDispatcher;
    shutdown(): void;
    setDocument(doc: Document): void;
    setOptions(options: Options): void;
    elementResize(): void;
    setPointerEventsEnabled(enabled: boolean): void;
    getPointerEventsEnabled(): boolean;
    private _browserSupportsPointerEvents;
    private _usePointerEvents;
    private _calculateElementOffset;
    private _initDocumentEvents;
    private _initCanvasEvents;
    bindEvents(canvasContainer: HTMLDivElement): void;
    private _bindDocumentEvent;
    private _bindCanvasEvent;
    private _unbindDocumentEvents;
    private _unbindCanvasEvents;
    unbindEvents(): void;
    private _convertEventCoordsToTargetCoords;
    focusInput(focus: boolean): void;
    private _setButtons;
    private _processMouseDown;
    private _processMouseMove;
    private _processMouseUp;
    private _processMousewheel;
    private _processDocumentMouseMove;
    private _processDocumentMouseUp;
    private _processMouseLeave;
    private _processMouseEnter;
    private _isFunctionKey;
    private _processKeyDownEvent;
    private _processKeyUpEvent;
    private _processTouchStart;
    private _processTouchMove;
    private _processTouchEnd;
    private _processPointerDown;
    private _processPointerMove;
    private _processPointerUp;
    private _processPointerEnter;
    private _processPointerLeave;
    private _processDocumentPointerMove;
    private _processDocumentPointerUp;
    private _getEventModifiers;
}
