import { Point3, Point4, Matrix } from '@ts3d-hoops/common';
export type Vector3 = [number, number, number];
export type Vector4 = [number, number, number, number];
export declare function toVec3(v: Point3): Vector3;
export declare function cwiseAbs3(v: number[]): Vector3;
export declare function cwiseProduct3(u: number[], v: number[]): Vector3;
export declare function add3(u: Vector3, v: Vector3): Vector3;
export declare function sub3(u: Vector3, v: Vector3): Vector3;
export declare function add4(u: Vector4, v: Vector4): Vector4;
export declare function sub4(u: Vector4, v: Vector4): Vector4;
export declare function dot3(u: number[], v: number[]): number;
export declare function squaredNorm3(v: number[]): number;
export declare function norm3(v: number[]): number;
export declare function scale3(k: number, v: Vector3): Vector3;
export declare function toVec4(v: Point4): Vector4;
export declare function row4(matrix: Matrix, rowIndex: number): Vector4;
export declare function col4(matrix: Matrix, colIndex: number): Vector4;
export declare function squaredNorm4(v: number[]): number;
export declare function scale4(k: number, v: Vector4): Vector4;
export declare function projectSquaredSize(center: Vector3, squaredSize: number, viewProjectionW: Vector4): number;
