import { IFloorplanService, OrientationName, AutoActivationModeName } from './types';
import { Floorplan } from '@ts3d-hoops/web-viewer';
export declare class FloorplanService extends EventTarget implements IFloorplanService {
    readonly serviceName: "FloorplanService";
    private _floorplanManager?;
    static readonly DefaultConfig: {
        floorplanActive: boolean;
        trackCamera: boolean;
        orientation: OrientationName;
        autoActivationMode: AutoActivationModeName;
        overlayFeetPerPixel: number;
        overlayZoomLevel: number;
        overlayBackgroundOpacity: number;
        overlayBorderOpacity: number;
        overlayAvatarOpacity: number;
        floorplanBackgroundColor: string;
        floorplanBorderColor: string;
        floorplanAvatarColor: string;
        floorplanAvatarOutlineColor: string;
    };
    constructor(floorplanManager?: Floorplan.FloorplanManager);
    get floorplanManager(): Floorplan.FloorplanManager | undefined;
    set floorplanManager(manager: Floorplan.FloorplanManager | undefined);
    isActive(): boolean;
    setActive(active: boolean): Promise<void>;
    isTrackCameraEnabled(): boolean;
    setTrackCameraEnabled(enabled: boolean): Promise<void>;
    getOrientation(): OrientationName;
    setOrientation(orientation: OrientationName): Promise<void>;
    getAutoActivationMode(): AutoActivationModeName;
    setAutoActivationMode(mode: AutoActivationModeName): Promise<void>;
    getOverlayFeetPerPixel(): number;
    setOverlayFeetPerPixel(feetPerPixel: number): Promise<void>;
    getOverlayZoomLevel(): number;
    setOverlayZoomLevel(zoomLevel: number): Promise<void>;
    getOverlayBackgroundOpacity(): number;
    setOverlayBackgroundOpacity(opacity: number): Promise<void>;
    getOverlayBorderOpacity(): number;
    setOverlayBorderOpacity(opacity: number): Promise<void>;
    getOverlayAvatarOpacity(): number;
    setOverlayAvatarOpacity(opacity: number): Promise<void>;
    getFloorplanBackgroundColor(): string;
    setFloorplanBackgroundColor(color: string): Promise<void>;
    getFloorplanBorderColor(): string;
    setFloorplanBorderColor(color: string): Promise<void>;
    getFloorplanAvatarColor(): string;
    setFloorplanAvatarColor(color: string): Promise<void>;
    getFloorplanAvatarOutlineColor(): string;
    setFloorplanAvatarOutlineColor(color: string): Promise<void>;
    resetConfiguration(obj?: object): Promise<void>;
    reset(): Promise<void>;
}
export default FloorplanService;
