import { IResettableConfigurationService, IService } from '../types';
export declare const OrientationNames: readonly ["North Up", "Avatar Up"];
export type OrientationName = (typeof OrientationNames)[number];
export declare function isOrientationName(value: unknown): value is OrientationName;
export declare const AutoActivationModeNames: readonly ["Bim", "Bim + Walk", "Never"];
export type AutoActivationModeName = (typeof AutoActivationModeNames)[number];
export declare function isAutoActivationModeName(value: unknown): value is AutoActivationModeName;
export type FloorplanServiceConfiguration = {
    floorplanActive: boolean;
    trackCamera: boolean;
    orientation: OrientationName;
    autoActivationMode: AutoActivationModeName;
    overlayFeetPerPixel: number;
    overlayZoomLevel: number;
    overlayBackgroundOpacity: number;
    overlayBorderOpacity: number;
    overlayAvatarOpacity: number;
    floorplanBackgroundColor: string;
    floorplanBorderColor: string;
    floorplanAvatarColor: string;
    floorplanAvatarOutlineColor: string;
};
export declare function isFloorplanServiceConfiguration(obj: unknown): obj is FloorplanServiceConfiguration;
export interface IFloorplanService extends IService, IResettableConfigurationService {
    isActive(): boolean;
    setActive(active: boolean): Promise<void>;
    isTrackCameraEnabled(): boolean;
    setTrackCameraEnabled(enabled: boolean): Promise<void>;
    getOrientation(): OrientationName;
    setOrientation(orientation: OrientationName): Promise<void>;
    getAutoActivationMode(): AutoActivationModeName;
    setAutoActivationMode(mode: AutoActivationModeName): Promise<void>;
    getOverlayFeetPerPixel(): number;
    setOverlayFeetPerPixel(feetPerPixel: number): Promise<void>;
    getOverlayZoomLevel(): number;
    setOverlayZoomLevel(zoomLevel: number): Promise<void>;
    getOverlayBackgroundOpacity(): number;
    setOverlayBackgroundOpacity(opacity: number): Promise<void>;
    getOverlayBorderOpacity(): number;
    setOverlayBorderOpacity(opacity: number): Promise<void>;
    getOverlayAvatarOpacity(): number;
    setOverlayAvatarOpacity(opacity: number): Promise<void>;
    getFloorplanBackgroundColor(): string;
    setFloorplanBackgroundColor(color: string): Promise<void>;
    getFloorplanBorderColor(): string;
    setFloorplanBorderColor(color: string): Promise<void>;
    getFloorplanAvatarColor(): string;
    setFloorplanAvatarColor(color: string): Promise<void>;
    getFloorplanAvatarOutlineColor(): string;
    setFloorplanAvatarOutlineColor(color: string): Promise<void>;
    resetConfiguration(obj?: object): Promise<void>;
    reset(): Promise<void>;
}
