import { DataKey, InclusionKey, InstanceKey, MeshKey, ModelKey } from '@ts3d-hoops/streamcache';
import { ScAttacher } from '../internal/tree/load/ScAttacher';
import { ProductOccurrence } from '../internal/tree/node/ProductOccurrence';
import { RepresentationItem } from '../internal/tree/node/RepresentationItem';
import { AnyBody, AnyNode, AnyNonTreeNode, AnyTreeContext, AnyTreeNode, DeletableNode, LoadId } from '../internal/tree/node/types';
import { AuthoredNodeId, DynamicNodeId, RuntimeNodeId } from '../internal/tree/NodeId';
import { BodyInstance } from '../internal/tree/node/BodyInstance';
import { BimId, FilteredNodes, FilterId, FilterName, GenericId, GenericType, LayerId, LayerName, NodeIdOffset, PmiSubType, PmiType, RelationshipType } from '../types';
import { Pmi } from '../internal/tree/node/Pmi';
import { CadView, CadViewParent } from '../internal/tree/node/CadView';
import { MeshInstanceData } from '../MeshData';
import { Matrix16, Plane, Point3 } from '@ts3d-hoops/common';
import { Camera } from '../Camera';
import { IScEngine } from './IScEngine';
import { IView } from './IView';
import { InclusionContext } from '../internal/tree/context/InclusionContext';
import { ReferenceOnTopology } from '../internal/tree/node-data/ReferenceOnTopology';
import { PartDefinition } from '../internal/tree/node/PartDefinition';
import { TreeLoader } from '../internal/tree/load/TreeLoader';
import { BimRelationship } from '../internal/tree/node-data/relationship/types';
import { AssemblyDataHeader } from '../internal/tree/AssemblyData';
import { LazyLike } from '../util';
import { AuthoredLayerId } from '../internal/tree/node-data/types';
import { PmiBody } from '../internal/tree/node/PmiBody';
import { LoadContext } from '../internal/tree/context/LoadContext';
import { Layer } from '../internal/tree/node-data/Layer';
import { Filter } from '../internal/tree/node-data/filter/Filter';
import { LazyPromise } from '../internal/LazyPromise';
import { SharedPrototypeContext } from '../internal/tree/context/PrototypeContext';
import { ViewFrame } from '../internal/tree/node/ViewFrame';
export interface IAssemblyTree {
    activateCadConfiguration(node: ProductOccurrence): void;
    activateCadView(view: IView, cadView: CadView, duration: number, massageCamera: boolean): Promise<void>;
    addFilter(filter: Filter, loadContext: LoadContext): void;
    allowNodeDeletion(node: DeletableNode): void;
    containsDrawings(): boolean;
    createCadView(engine: IScEngine, parent: CadViewParent, name: string, camera: Camera, pmis: Pmi[] | null, productOccurrencesToShow: RuntimeNodeId[], productOccurrencesToHide: RuntimeNodeId[], transformMap: Map<RuntimeNodeId, Matrix16>, cuttingPlane: Plane | null, meshInstanceData: MeshInstanceData | null): CadView;
    createLayer(authoredLayerId: AuthoredLayerId, layerName: LayerName | null, loadContext: LoadContext): Layer;
    createMeshInstance(markLoaded: boolean, inclusionKey: InclusionKey, instanceKey: InstanceKey, authoredId: AuthoredNodeId | null, name: string | null, parent: ProductOccurrence, preventFromResetting: boolean, isOutOfHierarchy: boolean, initiallyVisible: boolean, implicitBody: boolean): BodyInstance;
    createNode(parent: ProductOccurrence, nodeName: string, authoredId: AuthoredNodeId | null, localMatrix: Matrix16 | null, visibility: boolean, measurementUnit?: number | null): ProductOccurrence;
    createPart(authoredNodeId: AuthoredNodeId | null): PartDefinition;
    createPmiInstance(inclusionKey: InclusionKey, instanceKey: InstanceKey, authoredId: AuthoredNodeId | null, name: string | null, parent: ProductOccurrence, pmiType: PmiType, pmiSubType: PmiSubType, topoRefs: ReferenceOnTopology[]): Pmi;
    deactivateActiveCadView(): Promise<void>;
    deleteNode(node: ProductOccurrence | BodyInstance | Pmi): Promise<void>;
    disableAutomaticFitWorld(): boolean;
    enqueue<T>(lazyPromise: LazyLike<Promise<T>>): Promise<T>;
    forEachCadConfiguration(callback: (node: ProductOccurrence) => void): void;
    forEachCadView(callback: (node: CadView) => void): void;
    forEachPmi(callback: (node: Pmi) => void): void;
    generateDrawingSheetName(): string;
    generateDrawingViewName(): string;
    generateDynamicNodeId(): DynamicNodeId;
    generateGroupName(): string;
    generateProductName(): string;
    genericTypeToNodes(): Map<GenericType, Set<AnyTreeNode>>;
    getAbstractScEngine(): IScEngine;
    getActiveCadConfiguration(): ProductOccurrence | null;
    getAutomaticMeasurementUnitScaling(): boolean;
    getCadConfigurations(): ProductOccurrence[];
    getCadViewPmis(cadView: CadView): Pmi[];
    getDefaultCadConfiguration(): ProductOccurrence | null;
    getDefaultCadView(node: ProductOccurrence | null): CadView | null;
    getFilterName(filterId: FilterId): FilterName | null;
    getFilters(): Map<FilterId, FilterName>;
    getFiltersWithNode(targetNode: AnyTreeNode): FilterId[];
    getFirstProductOccurrenceWithView(): ProductOccurrence | null;
    getInclusionContexts(inclusionKey: InclusionKey): InclusionContext[];
    getInitiallyHiddenStayHidden(): boolean;
    getInstanceCountByInclusion(inclusionKey: InclusionKey): number;
    getLayersIdFromName(name: LayerName): LayerId[] | null;
    getLayerName(layerId: LayerId): LayerName | null;
    getLayerAuthoredId(layerId: LayerId): number | null;
    getLayers(): Map<LayerId, LayerName>;
    getLowestAvailableNodeId(): RuntimeNodeId;
    getNodesByGenericId(genericId: GenericId): Set<AnyTreeNode> | null;
    getNodesByGenericType(genericType: GenericType): Set<AnyTreeNode> | null;
    getNodesFromFilterIds(filterIds: FilterId[]): FilteredNodes | null;
    getNodesFromLayer(layerId: LayerId, onlyTreeNodes?: boolean): AnyTreeNode[] | null;
    getNodesFromLayerName(layerName: LayerName, onlyTreeNodes?: boolean): AnyTreeNode[] | null;
    getNodesFromLayers(layerIds: LayerId[], onlyTreeNodes?: boolean): AnyTreeNode[] | null;
    getRelationshipsOfItem(contextNodeId: RuntimeNodeId, node: BimId): Map<RelationshipType, BimRelationship>;
    getRootNode(): ProductOccurrence;
    getUniqueLayerNames(): LayerName[];
    hasActiveCadView(): boolean;
    initialize(scAttacher: ScAttacher): void;
    isBeingRequested(startNode: AnyTreeNode | AnyTreeContext): boolean;
    isInitialized(): boolean;
    isMeasurable(): boolean;
    lookupAnyBody(nodeId: RuntimeNodeId): AnyBody | null;
    lookupAnyBodyByInstanceInc(inclusionKey: InclusionKey, instanceKey: InstanceKey): AnyBody | null;
    lookupAnyNode(nodeId: RuntimeNodeId): AnyNode | null;
    lookupAnyNonTreeNode(nodeId: RuntimeNodeId): AnyNonTreeNode | null;
    lookupAnyTreeNode(nodeId: RuntimeNodeId): AnyTreeNode | null;
    lookupBodyInstance(nodeId: RuntimeNodeId): BodyInstance | null;
    lookupCadView(nodeId: RuntimeNodeId): CadView | null;
    lookupPartDefinition(nodeId: RuntimeNodeId): PartDefinition | null;
    lookupPartDefinitionByDataId(loadContext: LoadContext, modelKey: ModelKey, dataKey: DataKey): LazyPromise<PartDefinition> | null;
    lookupPmi(nodeId: RuntimeNodeId): Pmi | null;
    lookupPmiBody(nodeId: RuntimeNodeId): PmiBody | null;
    lookupProductOccurrence(nodeId: RuntimeNodeId): ProductOccurrence | null;
    lookupPrototypeByDataId(loadContext: LoadContext, modelKey: ModelKey, dataKey: DataKey): SharedPrototypeContext | null;
    lookupRepresentationItem(nodeId: RuntimeNodeId): RepresentationItem | null;
    lookupViewFrame(nodeId: RuntimeNodeId): ViewFrame | null;
    markImplicitNodesOutOfHierarchy(): boolean;
    markSeenExternalModel(): void;
    massageAuthoredUserId(inclusionContext: InclusionContext, authoredId: AuthoredNodeId | null): AuthoredNodeId | DynamicNodeId;
    newNodeIdOffset(): NodeIdOffset;
    onDemandRequestsActive(): boolean;
    onLoadBegin(): LoadId;
    onLoadEnd(loadId: number): void;
    preventMeshDeletion(meshKey: MeshKey): void;
    preventNodeDeletion(node: DeletableNode): void;
    registerBodyInstance(node: BodyInstance, inclusionKey: InclusionKey): void;
    registerCadView(node: CadView): void;
    registerGenericGlobalId(node: AnyTreeNode, genericId: GenericId): void;
    registerGenericType(node: AnyTreeNode, genericType: GenericType): void;
    registerInclusionContext(context: InclusionContext): void;
    registerNodeInLayer(node: AnyTreeNode, authoredLayerId: AuthoredLayerId): void;
    requestNodes(treeLoader: TreeLoader, nodes: AnyTreeNode[], isImplicitlyRequested: boolean): Promise<void>;
    registerPartDefinition(partDef: PartDefinition): void;
    registerPartDefinitionByDataId(loadContext: LoadContext, modelKey: ModelKey, dataKey: DataKey, partDefinition: LazyPromise<PartDefinition>): void;
    registerPmi(node: Pmi): void;
    registerPmiBody(node: PmiBody, inclusionKey: InclusionKey): void;
    registerProductOccurrence(node: ProductOccurrence): void;
    registerPrototypeByDataId(loadContext: LoadContext, modelKey: ModelKey, dataKey: DataKey, prototype: SharedPrototypeContext): void;
    registerRepresentationItem(repItem: RepresentationItem): void;
    registerTreeNodeInLayer(node: AnyTreeNode, authoredLayerId: AuthoredLayerId): void;
    registerViewFrame(node: ViewFrame, inclusionKey: InclusionKey): void;
    reset(): Promise<void>;
    seenExternalModel(): boolean;
    setAutomaticMeasurementUnitScaling(value: boolean): void;
    setInitiallyHiddenStayHidden(value: boolean): void;
    setPart(referrer: ProductOccurrence, partDef: PartDefinition): void;
    setViewAxes(frontVec: Point3, upVec: Point3): void;
    tryParseHeader(possibleHeaderData: Uint8Array): Promise<AssemblyDataHeader> | null;
    updateLayerName(layerId: LayerId, layerName: LayerName): void;
}
