import { InclusionKey, InstanceIncs, InstanceKey, MeshKey, ModelInc, ModelKey, ScModelName, ScsBuffer } from '@ts3d-hoops/streamcache';
import { Attribute, BimId, BranchVisibility, BranchVisibilityOptions, CadViewId, ExchangeId, FileType, FilteredNodes, FilterId, FilterName, GenericId, GenericType, IdStringMap, LayerId, LayerName, LoadSubtreeConfig, MassageModelNameFunc, ModelNameToScsFileFunc, NodeId, NodeIdOffset, NodeType, PmiSubType, PmiType, RelationshipInfo, RelationshipType, ScsUri, StringStringMap, UserDataIndex, XmlFilename } from '../types';
import { AuthoredNodeId, RuntimeNodeId } from '../internal/tree/NodeId';
import { BodyTypeBits } from '../internal/tree';
import { Box, Color, Matrix, Matrix16, Plane, Point3, UnitElement } from '@ts3d-hoops/common';
import { WalkRestriction } from '../internal/tree/traversal/types';
import { AnyBody, AnyNode, AnyTreeNode } from '../internal/tree/node/types';
import { Pmi, PmiTopologyReference } from '../internal/tree/node/Pmi';
import { Camera } from '../Camera';
import { MeshInstanceData } from '../MeshData';
import { SubentityAttributes } from '../SubentityAttributes';
import { Base, Edge, Face } from '../internal';
import { BodyInstance } from '../internal/tree/node/BodyInstance';
import { ReferenceOnTopology } from '../internal/tree/node-data/ReferenceOnTopology';
import { AssemblyData, AssemblyDataHeader } from '../internal/tree/AssemblyData';
import { ProductOccurrence } from '../internal/tree/node/ProductOccurrence';
import { CadView } from '../internal/tree/node/CadView';
import { PartDefinition } from '../internal/tree/node/PartDefinition';
import { RepresentationItem } from '../internal/tree/node/RepresentationItem';
import { IView } from './IView';
import { BimRelationship } from '../internal/tree/node-data/relationship/types';
import { Relationship } from '../internal/tree/node-data/relationship/Relationship';
export interface IModelStructure {
    activateCadConfiguration(view: IView, cadConfigId: RuntimeNodeId, fitNodes: boolean): Promise<void>;
    activateCadView(view: IView, cadViewId: RuntimeNodeId, duration: number, massageCamera: boolean): Promise<void>;
    activateDefaultCadView(view: IView, duration: number, massageCamera: boolean): Promise<void>;
    activateDefaultCadConfiguration(view: IView, fitNodes: boolean): Promise<void>;
    addProperty(nodeId: RuntimeNodeId, propertyName: string, propertyValue: string, propertyUnit: UnitElement[]): boolean;
    allowNodeDeletion(nodeId: NodeId): void;
    applyFilters(filterIds: FilterId[]): Promise<void>;
    cadConfigurationsEnabled(): Promise<boolean>;
    clear(): Promise<void>;
    createAndAddRepItem(partId: RuntimeNodeId, repItemId: AuthoredNodeId | null): RuntimeNodeId | null;
    createCadView(parentId: RuntimeNodeId, viewName: string, camera: Camera, pmiIds: RuntimeNodeId[] | null, nodesToShow: RuntimeNodeId[], nodesToHide: RuntimeNodeId[], nodesIdAndLocalTransforms: [RuntimeNodeId, Matrix][], cuttingPlane: Plane | null, meshInstanceData: MeshInstanceData | null): RuntimeNodeId | null;
    createMeshInstance(inclusionKey: InclusionKey, instanceKey: InstanceKey, name: string | null, parentId: RuntimeNodeId | null, preventFromResetting: boolean, isOutOfHierarchy: boolean, implicitBody: boolean): RuntimeNodeId;
    createNode(parentId: RuntimeNodeId | null, nodeName: string, nodeId: AuthoredNodeId | null, localMatrix?: Matrix | null, visibility?: boolean, measurementUnit?: number | null): RuntimeNodeId;
    createPart(nodeId: AuthoredNodeId | null): RuntimeNodeId;
    createPmiInstance(inclusionKey: InclusionKey, instanceKey: InstanceKey, pmiType: PmiType, pmiSubType: PmiSubType, topoRefs: ReferenceOnTopology[], name: string | null, parentId: RuntimeNodeId | null): RuntimeNodeId;
    deleteNode(nodeId: RuntimeNodeId): Promise<void>;
    firstAssemblyDataHeader(): AssemblyDataHeader | null;
    gatherInstanceIncsFromNodeIds(nodeIds: RuntimeNodeId[], allowedTypes: BodyTypeBits, restriction: WalkRestriction): InstanceIncs;
    /**
     * Walk the assembly tree from the given nodeId and gather all the AnyBody nodes found.
     * @param nodeId The starting nodeId to walk from.
     * @returns An array of AnyBody nodes found during the walk.
     */
    gatherAnyBodiesFromNodeId(nodeId: RuntimeNodeId): AnyBody[];
    getAbsoluteRootNodeId(): RuntimeNodeId;
    getActiveCadConfiguration(): RuntimeNodeId | null;
    getAllRelationships(nodeId: RuntimeNodeId): Relationship[];
    getAssociatedModelKey(nodeId: RuntimeNodeId): ModelKey | null;
    getAttributes(nodeId: RuntimeNodeId): Promise<Attribute[]>;
    getBimIdFromNode(nodeId: RuntimeNodeId): BimId | null;
    getBimIdRelationshipTypes(contextNodeId: RuntimeNodeId, nodeId: BimId): RelationshipInfo[];
    getBounding(nodeIds: RuntimeNodeId[], allowedTypes: BodyTypeBits, ignoreInvisible: boolean, tightBounding: boolean): Promise<Box>;
    getBranchVisibility(nodeId: RuntimeNodeId, options?: BranchVisibilityOptions): BranchVisibility;
    getCadConfigurations(): IdStringMap;
    getCadViewConfiguration(nodeId: RuntimeNodeId): RuntimeNodeId | null;
    getCadViewMap(): Map<NodeId, string>;
    getCadViewPmis(cadViewId: RuntimeNodeId): RuntimeNodeId[];
    getChildIds(nodeId: RuntimeNodeId, includeOutOfHierarchy: boolean): RuntimeNodeId[];
    getDefaultCadConfiguration(): RuntimeNodeId | null;
    getDefaultCadView(): RuntimeNodeId | null;
    getEdgeAttributes(nodeId: RuntimeNodeId, edgeId: number): Promise<SubentityAttributes | null>;
    getEdgeCount(nodeId: RuntimeNodeId): Promise<number>;
    getEdgeProperty(nodeId: RuntimeNodeId, edgeId: number): Promise<Edge | null>;
    getFaceAttributes(nodeId: RuntimeNodeId, faceId: number): Promise<SubentityAttributes | null>;
    getFaceCount(nodeId: RuntimeNodeId): Promise<number>;
    getFaceProperty(prcId: RuntimeNodeId, faceId: number): Promise<Face | null>;
    getFilters(): Map<FilterId, FilterName>;
    getFilterName(filterId: FilterId): FilterName | null;
    getFiltersWithNode(nodeId: RuntimeNodeId): FilterId[];
    getFiltersFromView(nodeId: CadViewId): FilterId[];
    getGenericTypeIdMap(): Map<GenericType, Set<RuntimeNodeId>>;
    getGenericTypes(): GenericType[];
    getIdOffset(nodeId: RuntimeNodeId): NodeIdOffset;
    getInfoOfBimId(nodeID: RuntimeNodeId, bimId: BimId): {
        name: string;
        connected: boolean;
    };
    getInstanceIncs(nodeId: RuntimeNodeId, allowedTypes: BodyTypeBits): InstanceIncs;
    getLayerName(layerId: LayerId): LayerName | null;
    getLayerAuthoredId(layerId: LayerId): number | null;
    getLayerIdsFromName(name: LayerName): LayerId[] | null;
    getLayers(): Map<LayerId, LayerName>;
    getLowestAvailableNodeId(): RuntimeNodeId;
    getMatrix(nodeId: RuntimeNodeId): Matrix;
    getModelFileNameFromNode(nodeId: RuntimeNodeId): string | null;
    getModelFileTypeFromNode(nodeId: RuntimeNodeId): FileType | null;
    getName(nodeId: RuntimeNodeId): string | null;
    getNetMatrix(nodeId: RuntimeNodeId): Matrix16;
    getNodeExchangeId(nodeId: RuntimeNodeId): ExchangeId | null;
    getNodeFromInstanceInc(markNodeLoadedIfCreated: boolean, inclusionKey: InclusionKey, instanceKey: InstanceKey, isOutOfHierarchy: boolean): RuntimeNodeId;
    getNodeGenericType(nodeId: RuntimeNodeId): GenericType | null;
    getNodeGenericId(nodeId: RuntimeNodeId): GenericId | null;
    getNodeLayerId(nodeId: RuntimeNodeId): LayerId | null;
    getNodeOrRepItem(node: AnyNode): Promise<ProductOccurrence | Pmi | CadView | PartDefinition | RepresentationItem | null>;
    getNodesFromFilterIds(filterIds: FilterId[]): FilteredNodes | null;
    getNodesByGenericId(genericId: GenericId): Set<RuntimeNodeId> | null;
    getNodesByGenericType(genericType: GenericType): Set<RuntimeNodeId> | null;
    getParentId(nodeId: RuntimeNodeId): RuntimeNodeId | null;
    getPartReferrers(nodeId: RuntimeNodeId): Promise<RuntimeNodeId[] | null>;
    getPmiSubType(pmiId: RuntimeNodeId): PmiSubType;
    getPmiTopologyReferences(pmiNodeId: RuntimeNodeId): PmiTopologyReference[] | null;
    getPmiType(pmiId: RuntimeNodeId): PmiType;
    getPmis(): IdStringMap;
    getPointAttributes(nodeId: RuntimeNodeId, pointId: number): Promise<SubentityAttributes | null>;
    getProperties(nodeId: RuntimeNodeId, computeFromChildren: boolean): Promise<StringStringMap | null>;
    getRelationsByTypeFromNode(contextNodeId: RuntimeNodeId, nodeId: BimId): Map<RelationshipType, BimRelationship> | null;
    getRuntimeNodeFromBimId(contextNodeId: RuntimeNodeId, bimId: BimId): RuntimeNodeId | null;
    getRuntimeNodesFromLayer(layerId: LayerId, onlyTreeNodes?: boolean): RuntimeNodeId[] | null;
    getRuntimeNodesFromLayerName(layerName: LayerName, onlyTreeNodes?: boolean): RuntimeNodeId[] | null;
    getRuntimeNodesFromLayers(layersId: LayerId[], onlyTreeNodes?: boolean): RuntimeNodeId[] | null;
    getType(nodeId: RuntimeNodeId): NodeType;
    getUniqueLayerNames(): LayerName[];
    getUnit(nodeId: RuntimeNodeId): number;
    getUserData(nodeId: RuntimeNodeId, index: UserDataIndex): Uint8Array;
    getUserDataIndices(nodeId: RuntimeNodeId): UserDataIndex[];
    hasEffectiveGenericType(nodeId: NodeId, genericType: GenericType): boolean;
    hasRelationships(nodeId: RuntimeNodeId): boolean;
    init(view: IView, maxConcurrentAttachments: number | null): Promise<void>;
    isACadDrawing(): boolean;
    isAnnotationView(cadViewNodeId: RuntimeNodeId): boolean;
    isCombineStateView(cadViewNodeId: RuntimeNodeId): boolean;
    isFaceMeasurable(bodyId: NodeId, faceIndex: number): Promise<boolean>;
    isIdValid(nodeId: RuntimeNodeId): boolean;
    isLineMeasurable(bodyId: NodeId, lineIndex: number): Promise<boolean>;
    isMeasurable(): boolean;
    isNodeLoaded(nodeId: RuntimeNodeId): boolean;
    isOutOfHierarchy(nodeId: RuntimeNodeId): boolean;
    isReady(): boolean;
    isVisible(nodeId: RuntimeNodeId): boolean;
    isWithinExternalModel(nodeId: RuntimeNodeId): boolean;
    loadMeasurementFromFile(zipFilename: string): Promise<void>;
    loadMeasurementFromJson(json: any): Promise<void>;
    loadMeasurementFromString(str: string): Promise<void>;
    loadSubtreeFromAssemblyData(nodeId: RuntimeNodeId, modelInc: ModelInc, assemblyData: AssemblyData, config: LoadSubtreeConfig): Promise<RuntimeNodeId[]>;
    loadSubtreeFromScsBuffer(nodeId: RuntimeNodeId, scsBuffer: ScsBuffer, config: LoadSubtreeConfig): Promise<RuntimeNodeId[]>;
    loadSubtreeFromScsFile(nodeId: RuntimeNodeId, scsFilename: ScsUri, config: LoadSubtreeConfig): Promise<RuntimeNodeId[]>;
    loadSubtreeFromScsXmlDoc(nodeId: RuntimeNodeId, xmlData: string | Document, modelNameToScs: ModelNameToScsFileFunc, config: LoadSubtreeConfig): Promise<RuntimeNodeId[]>;
    loadSubtreeFromScsXmlFile(nodeId: RuntimeNodeId, xmlFilename: XmlFilename, modelNameToScs: ModelNameToScsFileFunc, config: LoadSubtreeConfig): Promise<RuntimeNodeId[]>;
    loadSubtreeFromStream(nodeId: RuntimeNodeId, modelName: ScModelName, config: LoadSubtreeConfig): Promise<RuntimeNodeId[]>;
    loadSubtreeFromXmlDoc(nodeId: RuntimeNodeId, xml: string | Document, massageModelName: MassageModelNameFunc, config: LoadSubtreeConfig): Promise<RuntimeNodeId[]>;
    loadSubtreeFromXmlFile(nodeId: RuntimeNodeId, xmlFilename: XmlFilename, massageModelName: MassageModelNameFunc, config: LoadSubtreeConfig): Promise<RuntimeNodeId[]>;
    lookupAnyBody(nodeId: RuntimeNodeId): AnyBody | null;
    lookupAnyTreeNode(nodeId: RuntimeNodeId): AnyTreeNode | null;
    lookupBodyInstance(nodeId: RuntimeNodeId): BodyInstance | null;
    preventMeshDeletion(meshId: MeshKey): void;
    preventNodeDeletion(nodeId: NodeId): void;
    registerGenericId(node: AnyTreeNode, genericId: GenericId): void;
    registerGenericType(node: AnyTreeNode, genericType: GenericType): void;
    requestNodes(nodeIds: RuntimeNodeId[]): Promise<void>;
    reset(): Promise<void>;
    resetAllTransforms(): Promise<void>;
    resetAllVisibilities(): Promise<void>;
    resetPmiColor(startNodeId: RuntimeNodeId | undefined): void;
    resetToInitialMatrix(nodeId: RuntimeNodeId): Promise<void>;
    setBehaviorInitiallyHidden(value: boolean): void;
    setBodyNodesVisibility(startNode: AnyTreeNode, visibilityFormatter: boolean | ((node: AnyTreeNode) => boolean | undefined)): Promise<void>;
    setEdgeProperty(nodeId: RuntimeNodeId, edgeId: number, prop: Base): void;
    setEnableAutomaticUnitScaling(value: boolean): void;
    setFaceProperty(nodeId: RuntimeNodeId, faceId: number, prop: Base): void;
    setMatrix(nodeId: RuntimeNodeId, matrix: Matrix, setAsInitial: boolean): Promise<void>;
    setMatrices(nodeIds: RuntimeNodeId[], matrices: Matrix[], setAsInitial: boolean): Promise<void>;
    setMeshLevel(nodeIds: RuntimeNodeId[], meshLevel: number): void;
    setPart(nodeId: RuntimeNodeId, partId: RuntimeNodeId): boolean;
    setPhysicalProperties(nodeId: RuntimeNodeId, centerOfGravity: Point3, surfaceArea: number, volume: number): boolean;
    setPmiColor(color: Color, startNodeId: RuntimeNodeId | undefined): void;
    setPrefetchScsCutoffScale(prefetchCutoffScale: number): void;
    setVisibilitiesByMap(idToVisibility: Map<RuntimeNodeId, boolean>, initiallyHiddenStayHidden?: boolean): Promise<void>;
    setVisibilitiesByValue(nodeIds: RuntimeNodeId[], visibility: boolean, initiallyHiddenStayHidden: boolean | null): Promise<void>;
    shutdown(): void;
    switchToModel(newModelFilename: string): Promise<RuntimeNodeId[]>;
    waitForReady(): Promise<void>;
    _disableCadConfigurations(): Promise<void>;
    $mapBimRelationshipTypes(nodeId: BimId, relationships: Relationship[]): RelationshipInfo[];
}
