import { Box, Color, Matrix, Plane, Point2, Point3, Ray } from '@ts3d-hoops/common';
import { AntiAliasingMode, BloomLayerInfo, BlurIntervalUnit, ComparisonConfig, DrawMode, DrawStrategy, ElementType, GroundPlane, ImageBasedLightingOrientation, LightKey, DrawModeName, NodeId, PointShape, PointSizeUnit, Projection, SimpleReflectionAttenuation, SimpleReflectionAttenuationUnit, TransparencyMode, ViewOrientation, XRayGroup, XRayTransparencyMode } from '../types';
import { ViewKey } from '@ts3d-hoops/streamcache';
import { Camera } from '../Camera';
import { OverlayManager } from '../overlay';
import { DomElements } from '../internal/DomElements';
import { IncrementalPickConfig, PickConfig } from '../PickConfig';
import { CompositeSelectionItem, IncrementalSelectionId, NodeEntitySelectionItem, NodeSelectionItem, SelectionItem } from '../selection';
import { NavCube } from '../NavCube';
import { AxisTriad } from '../AxisTriad';
import { FloorplanManager } from '../floorplan';
import { OperatorManager } from '../OperatorManager';
import { InputMonitor } from '../internal/InputMonitor';
import { VerticalGradient } from '../VerticalGradient';
import { HiddenLineSettings } from '../settings/HiddenLineSettings';
import { Light } from '../Light';
export interface IView {
    readonly id: ViewKey;
    readonly domElements: DomElements;
    readonly overlayManager: OverlayManager;
    readonly floorplanManager: FloorplanManager;
    readonly operatorManager: OperatorManager;
    readonly inputMonitor: InputMonitor;
    readonly navCube: NavCube;
    readonly axisTriad: AxisTriad;
    addLight(light: Light): Promise<LightKey>;
    advanceIncrementalSelection(handle: IncrementalSelectionId): Promise<NodeSelectionItem[] | null>;
    beginConvexPolyhedronSelection(volumePlanes: Plane[], heuristicOrigin: Point3, config: IncrementalPickConfig): Promise<IncrementalSelectionId>;
    beginRayDrillSelection(rayCssOrigin: Point2, rayCssBoxRadius: number, config: IncrementalPickConfig): Promise<IncrementalSelectionId>;
    beginScreenSelectByArea(areaCssMin: Point2, areaCssMax: Point2, config: IncrementalPickConfig): Promise<IncrementalSelectionId>;
    beginSphereSelection(sphereCenter: Point3, sphereRadius: number, config: IncrementalPickConfig): Promise<IncrementalSelectionId>;
    compositePickFromPoint(point: Point2, config: PickConfig): Promise<CompositeSelectionItem>;
    clearLights(): void;
    centerCameraOnNode(nodeId: NodeId, duration?: number, camera?: Camera): Promise<void>;
    endIncrementalSelection(handle: IncrementalSelectionId): Promise<void>;
    endComparison(): void;
    fitBounding(bounding: Box, duration?: number, camera?: Camera): Promise<void>;
    fitNodes(ids: NodeId[], duration?: number): Promise<void>;
    fitWorld(duration?: number, camera?: Camera): Promise<void>;
    getAmbientLightColor(): Color;
    getAmbientOcclusionEnabled(): boolean;
    getAmbientOcclusionRadius(): number;
    getAntiAliasingMode(): AntiAliasingMode;
    getAxisTriad(): AxisTriad;
    getBackgroundColor(): VerticalGradient;
    getBackfacesVisible(): boolean;
    getBloomEnabled(): boolean;
    getBloomIntensityScale(): number;
    getBloomLayers(): BloomLayerInfo[];
    getBloomThreshold(): number;
    getBloomThresholdRampWidth(): number;
    getBoundingCalculationIgnoresInvisible(): boolean;
    getCamera(): Camera;
    getCanvasSize(): Point2;
    getDrawMode(): DrawMode;
    getDrawModeName(): DrawModeName;
    getDrawStrategy(): DrawStrategy;
    getEyeDomeLightingBlurSamples(): Promise<number>;
    getEyeDomeLightingBlurInterval(): Promise<number>;
    getEyeDomeLightingBlurEdgeDistance(): Promise<number>;
    getEyeDomeLightingEnabled(): Promise<boolean>;
    getEyeDomeLightingOpacity(): Promise<number>;
    getEyeDomeLightingShadingEdgeDistance(): Promise<number>;
    getFaceVisibility(): boolean;
    getFullCameraMatrix(): Matrix;
    getGoochBaseColorProminence(): number;
    getGoochBlue(): number;
    getGoochLuminanceShiftStrength(): number;
    getGoochYellow(): number;
    getGroundPlane(): GroundPlane;
    getHardEdgeColor(): Color;
    getHardEdgesEnabled(): boolean;
    getHardEdgeOpacity(): number;
    getHardEdgeThreshold(): number;
    getHardEdgeThresholdRampWidth(): number;
    getHiddenLineSettings(): HiddenLineSettings;
    getImageBasedLightingEnabled(): boolean;
    getImageBasedLightingIntensity(): number;
    getImageBasedLightingOrientation(): ImageBasedLightingOrientation;
    getInteractiveDrawLimitIncreaseEnabled(): Promise<boolean>;
    getLight(key: LightKey): Promise<Light | undefined>;
    getLightKeys(): Promise<LightKey[]>;
    getLightingEnabled(): boolean;
    getLineJitterEnabled(): boolean;
    getLineJitterInstanceCount(): number;
    getLineJitterRadius(): number;
    getLineJitterFrequency(): number;
    getLineVisibility(): boolean;
    getMassageExtremeCameras(): boolean;
    getNavCube(): NavCube;
    getPointShape(): Promise<PointShape>;
    getPointSize(): Promise<[number, PointSizeUnit]>;
    getProjectionMatrix(): Matrix;
    getProjectionMode(): Projection;
    getSilhouetteColor(): Color;
    getSilhouetteEnabled(): boolean;
    getSilhouetteOpacity(): number;
    getSilhouetteThreshold(): number;
    getSilhouetteThresholdRampWidth(): number;
    getSimpleReflectionBlurInterval(): [number, BlurIntervalUnit];
    getSimpleReflectionBlurSamples(): number;
    getSimpleReflectionEnabled(): boolean;
    getSimpleReflectionFadeAngle(): number;
    getSimpleReflectionOpacity(): number;
    getSimpleReflectionAttenuation(): SimpleReflectionAttenuation;
    getSimpleShadowBlurInterval(): number;
    getSimpleShadowBlurSamples(): number;
    getSimpleShadowColor(): Color;
    getSimpleShadowEnabled(): boolean;
    getSimpleShadowInteractiveUpdateEnabled(): boolean;
    getSimpleShadowOpacity(): number;
    getSimpleShadowResolution(): number;
    getViewMatrix(): Matrix;
    getViewOrientationCamera(orientation: ViewOrientation, bounding?: Box, preserveModelUp?: boolean): Promise<Camera>;
    getToonShadingBandCount(): number;
    getToonShadingSpecularFactor(): number;
    isolateNodes(nodeIds: NodeId[], duration?: number, fitNodes?: boolean, initiallyHiddenStayHidden?: boolean | null): Promise<void>;
    injectViewOrientationChangeEvent(): void;
    pickAllFromRay(ray: Ray, config: PickConfig): Promise<NodeEntitySelectionItem[]>;
    pickAllFromPoint(point: Point2, config: PickConfig): Promise<NodeEntitySelectionItem[]>;
    pickFromPoint(point: Point2, config: PickConfig): Promise<SelectionItem>;
    pickFromRay(ray: Ray, config: PickConfig): Promise<SelectionItem>;
    pointToWindowPosition(pt: Point2): Point2;
    projectPoint(source: Point3, camera?: Camera): Point3;
    raycastFromPoint(point: Point2): Ray | null;
    redraw(callback?: () => void): void;
    removeLight(key: LightKey): void;
    resetCamera(duration?: number): Promise<void>;
    setAmbientLightColor(value: Color): void;
    setAmbientOcclusionEnabled(enabled?: boolean): Promise<void>;
    setAmbientOcclusionRadius(radius: number): Promise<void>;
    setAntiAliasingMode(antiAliasingMode: AntiAliasingMode): Promise<void>;
    setBackfacesVisible(visible: boolean): Promise<void>;
    setBackgroundColor(top?: Color | null, bottom?: Color | null): Promise<void>;
    setBloomEnabled(value?: boolean): void;
    setBloomIntensityScale(value: number): void;
    setBloomLayers(layers: BloomLayerInfo[]): void;
    setBloomThreshold(value: number): void;
    setBloomThresholdRampWidth(value: number): void;
    setBoundingCalculationIgnoresInvisible(value: boolean): void;
    setCamera(camera: Camera | null, duration?: number): boolean;
    setDisplayIncompleteFrames(value: boolean): Promise<void>;
    setDrawMode(drawMode: DrawMode): Promise<void>;
    setDrawMode(drawMode: DrawModeName): Promise<void>;
    setEyeDomeLightingBlurEdgeDistance(value: number): Promise<void>;
    setEyeDomeLightingBlurInterval(value: number): Promise<void>;
    setEyeDomeLightingBlurSamples(value: number): Promise<void>;
    setEyeDomeLightingEnabled(enabled?: boolean): Promise<void>;
    setEyeDomeLightingOpacity(value: number): Promise<void>;
    setEyeDomeLightingShadingEdgeDistance(value: number): Promise<void>;
    setFaceVisibility(faceVisibility: boolean): Promise<void>;
    setGoochBaseColorProminence(prominence: number): void;
    setGoochBlue(blue: number): void;
    setGoochLuminanceShiftStrength(shiftStrength: number): void;
    setGoochYellow(yellow: number): void;
    setGroundPlane(plane: GroundPlane): void;
    setHardEdgeColor(value: Color): void;
    setHardEdgesEnabled(value?: boolean): void;
    setHardEdgeOpacity(value: number): void;
    setHardEdgeThreshold(degrees: number): void;
    setHardEdgeThresholdRampWidth(degrees: number): void;
    setImageBasedLightingEnabled(value: boolean): void;
    setImageBasedLightingEnvironment(data: Uint8Array | null): void;
    setImageBasedLightingIntensity(value: number): void;
    setImageBasedLightingOrientation(value: ImageBasedLightingOrientation): void;
    setInitialCamera(camera: Camera): void;
    setInteractiveDrawDelay(value: number): Promise<void>;
    setInteractiveDrawLimitIncreaseEnabled(enable: boolean): void;
    setLightingEnabled(enabled?: boolean): Promise<void>;
    setLineJitterEnabled(value?: boolean): void;
    setLineJitterFrequency(value: number): void;
    setLineJitterInstanceCount(value: number): void;
    setLineJitterRadius(value: number): void;
    setLineVisibility(lineVisibility: boolean): Promise<void>;
    setMassageExtremeCameras(value: boolean): void;
    setMinimumFramerate(minimum: number): void;
    setPointShape(shape: PointShape): Promise<void>;
    setPointSize(size: number, unit: PointSizeUnit): Promise<void>;
    setPointVisibilityTest(points: Point3[]): void;
    setProjectionMode(projectionMode: Projection): void;
    setSilhouetteColor(value: Color): void;
    setSilhouetteEnabled(value?: boolean): void;
    setSilhouetteOpacity(value: number): void;
    setSilhouetteThreshold(value: number): void;
    setSilhouetteThresholdRampWidth(value: number): void;
    setSimpleReflectionAttenuation(nearDistance: number, farDistance: number, unit?: SimpleReflectionAttenuationUnit): void;
    setSimpleReflectionBlurInterval(value: number, unit?: BlurIntervalUnit): void;
    setSimpleReflectionBlurSamples(value: number): void;
    setSimpleReflectionEnabled(value?: boolean): void;
    setSimpleReflectionFadeAngle(degrees: number): void;
    setSimpleReflectionOpacity(value: number): void;
    setSimpleShadowBlurInterval(value: number): void;
    setSimpleShadowBlurSamples(value: number): void;
    setSimpleShadowColor(color: Color): void;
    setSimpleShadowEnabled(value?: boolean): void;
    setSimpleShadowInteractiveUpdateEnabled(value?: boolean): void;
    setSimpleShadowOpacity(opacity: number): void;
    setSimpleShadowResolution(pixels: number): void;
    setStatisticsDisplayVisibility(visibility: boolean): Promise<void>;
    setToonShadingBandCount(bandCount: number): void;
    setToonShadingSpecularFactor(specularFactor: number): void;
    setTransparencyMode(mode: TransparencyMode): void;
    setViewOrientation(orientation: ViewOrientation, duration?: number, bounding?: Box): Promise<void>;
    setXRayColor(element: ElementType, color: Color, group?: XRayGroup): Promise<void>;
    setXRayOpacity(opacity: number, element?: ElementType): Promise<void>;
    setXRayTransparencyMode(mode: XRayTransparencyMode): Promise<void>;
    startComparison(nodeIdSet1: NodeId[], nodeIdSet2: NodeId[], config?: ComparisonConfig): void;
    testPointVisibility(points: Point3[]): Promise<number[]>;
    unprojectPoint(point: Point2, z: number): Point3 | null;
    unsetDefaultCamera(): void;
    updateCamera(camera: Camera): Camera;
    updateLight(key: LightKey, light: Light): void;
    unsetXRayColor(element: ElementType, group?: XRayGroup): Promise<void>;
    _setCameraPromise(camera: Camera, duration: number): Promise<void>;
    _setInitialView(duration: number): Promise<void>;
}
