import { BimMask, GenericType } from '../../types';
import { AnyTreeNode } from './node/types';
import { IScEngine } from '../../core/IScEngine';
import { IModelStructure } from '../../core/IModelStructure';
export declare const IfcColumn = "IFCCOLUMN";
export declare const IfcCovering = "IFCCOVERING";
export declare const IfcCurtainWall = "IFCCURTAINWALL";
export declare const IfcDoor = "IFCDOOR";
export declare const IfcRamp = "IFCRAMP";
export declare const IfcRoof = "IFCROOF";
export declare const IfcSlab = "IFCSLAB";
export declare const IfcSpace = "IFCSPACE";
export declare const IfcStair = "IFCSTAIR";
export declare const IfcStairFlight = "IFCSTAIRFLIGHT";
export declare const IfcTransportElement = "IFCTRANSPORTELEMENT";
export declare const IfcWall = "IFCWALL";
export declare const IfcWallStandardCase = "IFCWALLSTANDARDCASE";
export declare const IfcWindow = "IFCWINDOW";
export declare function hasEffectiveGenericType(startNode: AnyTreeNode, genericType: GenericType): boolean;
export declare function ifcAttributeToBimMask(value: string): BimMask;
export declare function registerBimNodes(attributeToMask: (value: string) => BimMask, engine: IScEngine, modelStructure: IModelStructure, startNode: AnyTreeNode, legacy_useAttributeTitle: string | null): Promise<void>;
